### ISSUE TITLE
Document usage of putout with a single rule or plugin 

### ISSUE THREAD

**Issue by sgilroy** [coderaiser/putout#10]
How can I use putout to apply a single rule, such as `remove-unused-variables`?

It would be helpful if there was a simple, documented approach for this. Ideally, it should be possible to do this with a single command and without creating a .putout.json file.

It seems that specifying a limited set of rules or plugins in the local .putout.json file does not by default disable rules or plugins specified in the [default putout.json](https://github.com/coderaiser/putout/blob/master/packages/putout/putout.json) file. That is, it seems that the local plugins are added to the default, instead of replacing them. For the rules, it appears as though certain rules are on by default (even without appearing in the default .putout.json file) and I have not found a comprehensive list of all rules.

Using `putout --disable-all source.js` seems to only disable rules which are currently violated in the source files being evaluated, not all rules comprehensively.

Further, the documentation seems to be somewhat redundantly duplicated between the top level readme https://github.com/coderaiser/putout/blob/master/README.md and the readme in the putout package https://github.com/coderaiser/putout/blob/master/packages/putout/README.md which I find confusing.

**Comment by coderaiser** [comment]
> How can I use putout to apply a single rule, such as remove-unused-variables?

There is no such possibility, but it is a good idea for a pull request. Most rules is enabled because it is a good practice. I use `putout` for my projects, and I think that good defaults is much better then copying config file again and again. Anyways I'm ready to listen your ideas about improvements. And we can work on a pull request, if you interested. 

> Using putout --disable-all source.js seems to only disable rules which are currently violated in the source files being evaluated, not all rules comprehensively.

That's how it works, disable only what find.

> Further, the documentation seems to be somewhat redundantly duplicated between the top level readme https://github.com/coderaiser/putout/blob/master/README.md and the readme in the putout package https://github.com/coderaiser/putout/blob/master/packages/putout/README.md which I find confusing.

That's right, because first one you see when you open repository, and second one you see in [npm](https://www.npmjs.com/package/putout).

**Comment by oprogramador** [comment]
me too, I'd like to fix only `remove-unused-variables`

**Comment by oprogramador** [comment]
I opened https://github.com/oprogramador/putout/pull/1

**Comment by coderaiser** [comment]
@oprogramador could you please tell me why do you need it :)? There is a lot useful rules, why to disable them?

**Comment by oprogramador** [comment]
@coderaiser 

Because I want to only remove unused variables and the rest handle either with eslint autofix or manual updates.

**Comment by coderaiser** [comment]
The thing is `autofix` of `eslint` does nothing that `putout` do, so I think you should try to use other rules as well.
From the first day `putout` was made to supplement what `eslint` does and do nothing that `eslint` already does.

So `putout` is more about logic, and eslint is more about formatting.

**Comment by oprogramador** [comment]
`putout example.js --no-config --plugins remove-unused-variables` works fine, thanks
