### ISSUE TITLE
README has 404 linking to codemod plugin-convert-tape-to-supertape

### ISSUE THREAD

**Issue by jamos99** [coderaiser/putout#103]
Readme has a 404 in the [codemods section](https://github.com/coderaiser/putout#-codemods), links to https://github.com/coderaiser/putout/tree/master/codemods/plugin-convert-tape-to-supertape

I'd PR a fix if that codemod folder still existed, but it seems to be from another time?

**Comment by coderaiser** [comment]
Yes, this is from another time, I just fixed the link. The thing is codemod became [@putout/plugin-tape](https://github.com/coderaiser/putout/tree/master/packages/plugin-tape#readme) and I forget to update the link 😅.

Thank you!
