### ISSUE TITLE
Can I use this to extend JavaScript functionalities?

### ISSUE THREAD

**Issue by Bellisario** [coderaiser/putout#104]
I tried the live editor but I'm not sure if what I'm doing it's correct or not:
I would like, for example, use "func" instead of "function" into my code, so parse the token and replace with the valid JS one, but it outs always syntax error, also using "acorn" with "loose" checked.

I tried with this
```js
module.exports.replace = () => ({
    'func': 'function',
});
```

Is what I would like to do buildable or not?

**Comment by coderaiser** [comment]
If you want to use `func` inside your code, like this:

```js
func hello() {
    return 'world';
}
```

This will not be correct JavaScript, so `@babel/parser`, and any other `ESTree`-parser cannot  parse it to [`FunctionDeclaration`](https://github.com/estree/estree/blob/master/es5.md#functiondeclaration) node.

Anyways you can extend [`acorn`](https://github.com/acornjs/acorn#plugin-developments) to have support of `func`, and produce `FunctionDeclaration`, and use it in 🐊**Putout** with changes in `.putout.json`:

```json
{
    "parser": "my-parser-with-func-support"
}
```

This will work!

**Comment by Bellisario** [comment]
I was trying to extend javascript functionalities (like doing another programming language), just to try...

Thanks for your help :smile:, I'll close this issue (there is no need to let it open, there is no bug :bug:)

**Comment by coderaiser** [comment]
@Bellisario That's really interesting idea, if you have any issues, write me, I'll help you if I can. Do you have any other ideas for the syntax of programming language you want to make?

As for me, I prefer `Rust's` way of declaring a function with a keyword `fn`, this is really good:

```rust
fn hello() {
    "world"
}
```

This is the same as:

```js
function hello() {
    return 'world';
}
```

**Comment by Bellisario** [comment]
Yes @coderaiser, for example I liked to add "Swift guard statement" (not so useful but interesting) and, another one, add the "unfunc" statement like the Self Executing Function, but written like a JS unnamed function, for now, that's it...

I already wrote a very "twisted" code using a lot of regex matches and IFs for the tokenizer and the transpiler (that transform to "clean" JS code) and I was looking for something more simply, but seems there is nothing good for me...

My actual problem is that all my regex matches works because first of another and the first match of the code I wrote, this makes a function call (ex. `example()`) different for a variable call (ex. `thisIsAVarCall`) only because it matches first. If the var call check is putted before the function one, my result would be a example var call and total parenthesis ignore...

If you're interested on more of this (and want contribute, feel free... :stuck_out_tongue_winking_eye: ) I'll try to "clean" my quick made (debugging) test files, some unnecessary code (and so on...) and add to GitHub ASAP... :wink:

**Comment by coderaiser** [comment]
Yes, RegExp not really suited for parsing programming languages :)…

Could you please show me code examples of language you want and JavaScript alternatives.

**Comment by coderaiser** [comment]
OK, this is the simplest possible plugin to `acorn` that adds support of `fn` keyword:

```js
const {TokenType} = require('acorn');

function newSpeak(Parser) {
    Parser.acorn.keywordTypes['fn'] = new TokenType('fn',{keyword: 'fn'});
    
    return class extends Parser {
        parse() {
            this.keywords = addKeyword('fn', this.keywords);
            return super.parse();
        }
        parseStatement(context, topLevel, exports) {
            if (this.type == Parser.acorn.keywordTypes['fn']) {
                this.type = Parser.acorn.keywordTypes['function'];
            }
            return super.parseStatement(context, topLevel, exports);
        }
    }
}

function addKeyword(keyword, keywords) {
    const str = keywords
        .toString()
        .replace(')$', `|${keyword})$`)
        .slice(1, -1);
    
    return RegExp(str);
}
const {Parser} = require('acorn')
const newSpeak = require('./index.js');

const MyParser = Parser.extend(
    newSpeak,
)

console.log(MyParser.parse(`
    fn hello() {
        return 'world';
    }
`))
```

Got some information from [stackoverflow](https://stackoverflow.com/questions/59804600/how-to-add-keyword-to-acorn-or-esprima-parser).

This way is much better then RegExp's :)...

**Comment by Bellisario** [comment]
Thanks @coderaiser, that's very good for "custom" keywords, but what if I need to add a new statement?

I would like to add Guard Statement, but I don't think it's possible because of limitations extending the parser.

My example code would be:

```js
// should return "Hello " + "my text"
fn hello(text) {
  /* this is the actual guard
      should return an empty string if text === "world"
      could be compiled in JS so:
      if (!(text !== "world") {
        return ""
      }
      inverts condition to run only when the guard original condition is false

      we could say: "it checks text var is different from a value" and makes sure to run the code inside it only to fallback
  */
  guard (text !== "world") else {
    return ""
  }
  return "Hello " + text
}

hello("Tom") // returns "Hello Tom"
hello("world") // returns "" (an empty string)
```

I tried adding the "guard" keyword to your code and change the type to "ifStatement" (without invert condition, just to try the result), obviously because I have the "else" keyword after the "custom" if, the parser throws an error.

I think I should extend also "parseIfStatement" and maybe other of the original parser, but even by "studying" acorn source code I didn't find the solution...

**Comment by coderaiser** [comment]
This is very strange construction, but why not :)

```js
'use strict';

const {TokenType, tokTypes: tt} = require('acorn');

function newSpeak(Parser) {
    Parser.acorn.keywordTypes.fn = new TokenType('fn', {
        keyword: 'fn',
    });
    
    Parser.acorn.keywordTypes.guard = new TokenType('guard', {
        keyword: 'guard',
    });
    
    return class extends Parser {
        parse() {
            const keywords = addKeyword('fn', this.keywords);
            this.keywords = addKeyword('guard', keywords);
            
            return super.parse();
        }
        parseStatement(context, topLevel, exports) {
            if (this.type === Parser.acorn.keywordTypes.fn) {
                this.type = Parser.acorn.keywordTypes.function;
            }
            
            if (this.type === Parser.acorn.keywordTypes.guard) {
                return this.parseGuard(context, topLevel, exports);
            }

            return super.parseStatement(context, topLevel, exports);
        }
        
        parseGuard() {
            this.next();

            const node = this.startNode();
            
            this.expect(tt.parenL);
            
            node.test = {
                type: 'UnaryExpression',
                operator: '!',
                prefix: true,
                argument: this.parseExpression(),
            };
            this.expect(tt.parenR);
            this.expect(tt._else);
    
            node.consequent = this.parseStatement();
            node.alternate = null;
            
            return this.finishNode(node, 'IfStatement');
        }
    };
};

function addKeyword(keyword, keywords) {
    const str = keywords
        .toString()
        .replace(')$', `|${keyword})$`)
        .slice(1, -1);
    
    return RegExp(str);
}

const {print} = require('putout');
const {Parser} = require('acorn');
const newSpeak = require('./index.js');

const {stringify} = JSON;

const MyParser = Parser.extend(
    newSpeak,
);

const ast = MyParser.parse(`
    fn hello() {
        guard (text !== "world") else {
            return ""
        }
        
        return "Hello " + text
    }
`);

console.log(stringify(ast, null, 4));

console.log(print(ast));
// returns
`
function hello() {
    if (!(text !== 'world')) {
        return '';
    }

    return 'Hello ' + text;
}
`
```

**Comment by coderaiser** [comment]
Just created the [repository](https://github.com/coderaiser/goldstein), we can move there and continue to add new keywords :).

It already has ability to write tests, and extend in any way using TDD.
