### ISSUE TITLE
Can you put some simple guides together? I just want to modify a literal but can't figure out how.

### ISSUE THREAD

**Issue by reywright** [coderaiser/putout#108]
One of the things I want to do is this:

```js
<Component className="foo bar baz" />
const obj = { 
  key: "foo bar baz"
}
```

I want to be able to take a dictionary:

```js
{
  bar: 'apple',
  baz: 'orange'
}
```

and morph the code like so:

```js
<Component className="foo apple orange"  />
const obj = { 
  key: "foo apple orange"
}
```

In general it just may be a too high level vs jscodeshift which isn't as maintained but I can't really wrap my head around this tool and how to do things with it.

**Comment by coderaiser** [comment]
OK, here is the simplest [possible solution]( https://putout.cloudcmd.io/#/gist/a68565b7fb50d04525fc02df76c8fb08/7eb887fdbe9303eefe5531684806e2696a39afe4):

```js

module.exports.fix = (path) => {
    let {value} = path.node;
    const keys = path.node.value.split(' ');
    
    const obj = {
      bar: 'apple',
      baz: 'orange'
    }
    
    for (const key of keys) {
        if (!obj[key])
            continue;
        
        value = value.replace(key, obj[key]);
    }
    
    path.node.value = value;
}

module.exports.traverse = ({push}) => ({
    StringLiteral(path) {
        push(path);
    }
});
```

This is type of plugin called [Traverser](https://github.com/coderaiser/putout/tree/master/packages/engine-runner#traverser). It has method `traverse`, and `pushes` everything that is needed to `fix`, and `fix` do all the magic :).

Actually, you will need something a bit sophisticated. `StringLiteral` most likely will have some conditions to filter.

Also you may want to pass your `obj` with an `options`:

```js
module.exports.fix = (path, {options}) => {
    let {value} = path.node;
    const keys = path.node.value.split(' ');
    
    const {obj} = options;
    
    for (const key of keys) {
        if (!obj[key])
            continue;
        
        value = value.replace(key, obj[key]);
    }
    
    path.node.value = value;
}
```

Which you can pass then via `.putout.json`:

```json
{
    "rules": {
        "modify-literal": ["on", {
            "bar": "apple",
            "baz" "orange"
        }]
    }
}
```

**Comment by coderaiser** [comment]
@reywright is it works for you?

**Comment by reywright** [comment]
This does work, thank you!

**Comment by coderaiser** [comment]
Nice :)! Could you please tell me why do you need such kind of a transform?
