### ISSUE TITLE
remove-unsued-* doesn't work as expected  with unused destructured parameters

### ISSUE THREAD

**Issue by mrkosima** [coderaiser/putout#109]
Hello there, 
First of all, thanks for the supporting of the amazing library!

I bumped into an issue I can't sole with the tools from the box.

There's the code:

```js
export const func = (param) => { 
  const { a: { b }, c } = param;
  return c;
}
```

**Expected** - I want it to become :

```js
export const func = (param) => { 
  const { c } = param;
  return c;
}
```

**Actual** - but the only I could achieve is:

```js
export const func = (param) => { 
  const { a: { }, c } = param;
  return c;
}
```

I tried different rules combinations from the plugins:
```json
[
    "@putout/plugin-remove-unused-variables",
    "@putout/plugin-remove-unreferenced-variables",
    "@putout/plugin-split-nested-destructuring",
    "@putout/plugin-remove-useless-variables"
]
```

But no luck.

Could you please help me to understand how to fix the issue?

**Comment by coderaiser** [comment]
Just landed ability to remove empty nested patterns in [`@putout/plugin-remove-empty`](https://github.com/coderaiser/putout/tree/master/packages/plugin-remove-empty#nested-pattern) 🎉 .
Please install 🐊Putout [v27.5.0](https://github.com/coderaiser/putout/releases/tag/v27.5.0).

Is it works for you?

**Comment by mrkosima** [comment]
I updated and it works for me! 🎉
Thanks for the quick response!
