### ISSUE TITLE
convert-* rules in .putout.json are not respected if target file is located in another npm package

### ISSUE THREAD

**Issue by mrkosima** [coderaiser/putout#110]
Hi there, it feels like an issue, but please correct me if I'm wrong.

I have the following code structure:

---
##### package for putout setup
- `putout-runner/`
  - `node_modules/...`
  - `.putout.json` with config
     - `{ "rules": { "convert-esm-to-commonjs": "off", ... }}`
  - `package.json`
---
##### package with my appliation
- `my-app/` 
   - `node_modules/...`
   -  `src/`
       -  `main.js` - js code with esm syntax
   - `package.json`
---

When I run codemod from `putout-runner/` directory, it results in converting `/my-app/src/main.js` to `cjs` module:
`npm run putout --fix <path-to-the-projects>/my-app/src/main.js`

When I place `main.js` file into `putout-runner/` folder, the script does the thing I expect with keeping `esm` syntax.

I roughly debugged the _putout_ scripts and noticed the logic in [putout/parse-options/index.js :: _readOptions](https://github.com/coderaiser/putout/blob/master/packages/putout/lib/parse-options/index.js#L86). In my case the method [applyModuleTypeRules](https://github.com/coderaiser/putout/blob/master/packages/putout/lib/parse-options/apply-module-type-rules.js#L15) adds the configuration that I can't override:
```js
function commonjs() {
  return {
    match: {
      '*.js': {
        'convert-esm-to-commonjs': 'off',
      },
....
```

Could you please help me with the issue?

**Comment by coderaiser** [comment]
Actually it is a feature :), the logic is: take a look at `package.json` and if `type=module` handle file as ESM, and if `type=CommonJS` as CommonJS and convert it accordingly.

**Comment by mrkosima** [comment]
Alright, that's a nice feature, but how can I turn it off? 😄 
I expected that the rule in `.putout.json` overrides this behaviour, but apparently it does not.

Also `my-app/package.json` doesn't have `type` property. Is it intended that the module is treated as a `cjs` in this case?

**Comment by coderaiser** [comment]
> Also my-app/package.json doesn't have type property. Is it intended that the module is treated as a cjs in this case?
Yes, no type is `cjs`

According to https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#type it's good to have type mentioned directly or you can use `.mjs` file extension to show explicitly that you are using `esm`.

Anyways, you can add `.putout.json` in a directory with project you want to lint and turn off any rule you want :).

**Comment by mrkosima** [comment]
That's a good point, and I'd be glad to follow this approach. But it's not possible in my case, maybe because it's too specific.

To give you more context, I've built a library, and planning to released a new version with some breaking changes. With the new release I want to rollout a `codemod`. It's intended that the script will run over the code of the library consumers. I'm not own it, and want to make only point changes. So I can't modify module type in `package.json` nor adding `.putout.json` there.

Currently I patch putout's `apply-module-type-rules.js` to avoid conversion changes. 
Now for my case, I see that I can add `.putout.json` in the project I want to modify, run the _codemod_, and delete the config file.

But I would appreciate if there is a simpler way :)

**Comment by coderaiser** [comment]
What do you think about writing a 🐊**Putout** plugin and releasing it as `putout-plugin-name-of-your-library`, in this case you will have:
- ability to run your plugin in IDE, since `eslint-plugin-putout` runs plugins according to your config;
- have tests, and list of all modifications;
- have semantic versioning;
- use `putout` CLI to run your codemods;

Take a look at examples:
- [webpack](https://github.com/coderaiser/putout/tree/master/packages/plugin-webpack#readme);
- [jest](https://github.com/coderaiser/putout/tree/master/packages/plugin-jest#readme);

The main purpose of 🐊**Putout** is ability to level up the culture of codemods, so it was not one run from CLI, but more a linter plugin :).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝. Feel free to reopen :).
