### ISSUE TITLE
Traverse called twice

### ISSUE THREAD

**Issue by nkabir1986** [coderaiser/putout#112]
I have code for example :

```js
import * as acorn from "@acorn";
import letix from "@letix";
import detect,{show,hide} from "@detector";
import { get,set } from "@restack/server";
```

and write plugin with this config : 

```js
{
report: () => "",
fix: function (path) {
    console.log(path.node.source.value);
},
traverse: ({ push, listStore }) => ({
		ImportDeclaration(path) {
			listStore(path);
		},

		Program: {
			exit: () => {
				for (const path of listStore()) push(path);
			},
		},
	})
}
```

why traverse called two time for each importdeclaration and push each path two time to list  and fix called twice

**Comment by coderaiser** [comment]
Could you please tell me how do you run the code and why do you want to limit `fixCount`?
You have no changes in `fix` applied, so `traverse` called again.

**Comment by nkabir1986** [comment]
I need to parse all imports but i dont want to fix them . This plugin not completed and i want to remove functions and exports contains jsx and fix apply to them . But for performance i want to parse imports and store it in external variable to pervent more need to generate ast

**Comment by coderaiser** [comment]
`fix` set to run twice to see when plugin works wrong, for example with [`noReportAfterTransform()`](https://github.com/coderaiser/putout/tree/master/packages/test#noreportaftertransformfilename) helps to identify such cases.

**Comment by nkabir1986** [comment]
> `fix` set to run twice to see when plugin works wrong, for example with [`noReportAfterTransform()`](https://github.com/coderaiser/putout/tree/master/packages/test#noreportaftertransformfilename) helps to identify such cases.

tnx for ur help, i must use another way to handle this situation

**Comment by coderaiser** [comment]
What kind of situation? Could you provide more details: input and output examples

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝. Feel free to reopen :).
