### ISSUE TITLE
recordAndTuple somehow doesn't use the default value

### ISSUE THREAD

**Issue by dotai2012** [coderaiser/putout#114]
**Version used:**

- putout: 27.13.0
- eslint-plugin-putout: 16.3.0

**Problem:**

I am using putout in 2 of my projects

1. Nestjs server
2. React app

In the React app, it works seamlessly. However, the Nestjs server throws an error related to **_recordAndTuple_** (both of them use the same eslint's config)

![image](https://user-images.githubusercontent.com/12532557/197358811-9e28e36d-7186-4a56-8d0b-fca12eccd2fe.png)

`'recordAndTuple' requires 'syntaxType' option whose value should be one of: 'hash', 'bar'`

**Temporary fix:**

For those encounter this error, just revert this change:

https://github.com/coderaiser/putout/commit/7ffd1fbb64a9985ab08e0ef222926799f3785f00

However, it's so weird. I think it should have worked because 'hash' is the default value:

**Comment by coderaiser** [comment]
What version of babel are you using? Since [v7.19](https://babeljs.io/blog/2022/09/05/7.19.0#new-default-values) `hash` is default value.

**Comment by coderaiser** [comment]
I can't reproduce this, could you please make minimal project setup repo so I can try it?

I used:

```sh
$ npm i -g @nestjs/cli
$ nest new project-name
$ cd project-name
$ npm i putout eslint-plugin-putout -D
$ putout .
$ eslint .
```

It has same warnings related to `json` files thrown by `@typescript-eslint/parser` but nothing related to record and tuples.

**Comment by dotai2012** [comment]
Thank you for your help

I resolved the issue by removing node_modules + yarn.lock and reinstalling it again
