### ISSUE TITLE
remove-useless-spread/array   -- You should pay attention to sparse arrays

### ISSUE THREAD

**Issue by rambo-panda** [coderaiser/putout#119]
* rules :  [remove-useless-spread/array](https://github.com/coderaiser/putout/tree/master/packages/plugin-remove-useless-spread)
* current 
```js
[...Array(16)].map(v => {...});

//  change to

Array(16).map(v => {...});  // TODO: Sparse arrays cannot be iterated with higher-order functions
```

```diff
     'for (const __a of [...__b]) __c': 'for (const __a of __b) __c',
     'Array.from([...__a])': 'Array.from(__a)',
+    '[...Array(__args)]': 'Array.from(Array(__args))',
     '[...__a(__args)]': '__a(__args)',
     'new Set([...__a])': 'new Set(__a)',
```

**Comment by coderaiser** [comment]
> `[... a]` usually for copying

The thing is `[...b]` can be used for:
- copying an array;
- converting different value type like `string` to an `array`.

So better to be more concrete in and use `slice` for copying and `Array()` for converting to decrease cognitive load.
Also sometimes there is no need on any of this operations, and we can drop `spread`.

> `Array(16).map(v => {...});  // TODO: Sparse arrays cannot be iterated with higher-order functions`

This is a very good point!

**Comment by coderaiser** [comment]
> `[... a]` usually for copying

The thing is `[...b]` can be used for:
- copying an array;
- converting different value type like `string` to an `array`.

So better to be more concrete in and use `slice` for copying and `Array()` for converting to decrease cognitive load.
Also sometimes there is no need on any of this operations, and we can drop `spread`.

> `Array(16).map(v => {...});  // TODO: Sparse arrays cannot be iterated with higher-order functions`

This is a very good point!

**Comment by coderaiser** [comment]
> `[... a]` usually for copying

The thing is `[...b]` can be used for:
- copying an array;
- converting different value type like `string` to an `array`.

So better to be more concrete in and use `slice` for copying and `Array()` for converting to decrease cognitive load.
Also sometimes there is no need on any of this operations, and we can drop `spread`.

> `Array(16).map(v => {...});  // TODO: Sparse arrays cannot be iterated with higher-order functions`

This is a very good point!

**Comment by coderaiser** [comment]
Landed ability to ignore `Array()` constructor calls with numeric `argument` in `@putout/plugin-remove-useless-spread@6.1.0`. Please re-install 🐊**Putout**. Is it works for you?

**Comment by rambo-panda** [comment]
I am very sorry to reply so long because I was ill during this period.
At present, I am reconstructing a project, and I accidentally see your work
