### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by coderaiser** [coderaiser/putout#12]
According to [ci](https://travis-ci.org/coderaiser/putout) or `npm run coverage` in the root of repository.
There is some red places, would be great to add tests for them in the similar to existing tests.

**Comment by jmlavoier** [comment]
Assign it to me.

**Comment by coderaiser** [comment]
@jmlavoier If you have any trouble with running or writing tests ask, and I help.
It can be:

- [putout](https://github.com/coderaiser/putout/tree/master/packages/putout):
```sh
 codeframe.js     |    28.57 |       6,8,9,11,15 |
 eslint.js        |    82.54 |... 42,144,145,149 |
 ignores.js       |    37.5  |      7,8,10,11,13 |
 parse-options.js |    26.79 |... 18,119,121,126 |
```
- [engine-loader](https://github.com/coderaiser/putout/tree/master/packages/engine-loader):

```sh
 index.js                  |    96    |             12,39 |
  parse-plugin-names.js    |    80    |          16,17,18 |
  parse-rules.js           |    78.72 |... 14,119,120,122 |
  wrap-plugin.js           |      100 |                23 |
  jscodeshift.js           |    96    |                28 |
```
- [engine-runner](https://github.com/coderaiser/putout/tree/master/packages/engine-runner):
```sh
 get-position.js    |  88.89   |                11 |
  include.js        |       100|             10,12 |
  index.js          |    98.21 |               114 |
 lib/template
  index.js          |    95.56 |             12,24 |
```
- [eslint-plugin-putout](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout):

```sh
 for-of-multiple-properties-destructuring.js |    91.67 |                22 |
 long-properties-destructuring.js            |       95 |                62 |
 new-line-function-call-arguments.js         |    95.24 |                36 |
 putout.js                                   |     87.5 |          20,22,47 |
```

- [@putout/compare](https://github.com/coderaiser/putout/tree/master/packages/compare):

```
 compare.js                                   |     87.5 |          20,22,47 |
```

Or any other `package`, only remember that [plugin-react-hooks](https://github.com/coderaiser/putout/tree/master/packages/plugin-react-hooks) least important, because it not installed and used in `putout`, by default, so it's not core features (anyways if you find that this is simplest and more pleasurable  case, that's still OK 🙂.

**Comment by jmlavoier** [comment]
@coderaiser Great! Thanks for clearing up the coverage priorities. If I have some question, I ask here.

**Comment by jmlavoier** [comment]
I'm sorry for the delay. I've just sat for doing it today. I did just `codeframe.js` tests to know whether I'm going in the right way. After your approve I'll move forward to another file.

**Comment by coderaiser** [comment]
Closed due to 100% coverage :tada:
