### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by rambo-panda** [coderaiser/putout#120]
first of all, thank you for your project.  

There are two suggestions

* I hope there is an option in `cli` to show **all supported rules**
* ` path is missing for ruler toggler (--enable-all, --disable-all)`
    sometimes I just want to quickly *disable* a rule and fill the `.putout.json`

**Comment by coderaiser** [comment]
Hi, thank you. That's a good idea, the only thing **all supported rules** are different according to [`match`](https://github.com/coderaiser/putout#match), [`rulesdir`](https://github.com/coderaiser/putout#rulesdir), and content of `~/.putout`.

To make it possible [`putout/parse-options`](https://github.com/coderaiser/putout/blob/v28.0.1/packages/putout/lib/parse-options/index.js#L23) should be reused, are you up for a PR?
