### ISSUE TITLE
Customizing `tools` file path

### ISSUE THREAD

**Issue by rambo-panda** [coderaiser/putout#121]
eg: `isNumber`  `tryToCatch`  . We have implemented these methods, so we hope to provide a option to specify the `tools` file

**Comment by coderaiser** [comment]
Could you please provide more information?

**Comment by coderaiser** [comment]
Use `dismiss` option for [`declare-undefined-variables`](https://github.com/coderaiser/putout/tree/v28.1.0/packages/plugin-declare-undefined-variables#rules) rule.
