### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by rambo-panda** [coderaiser/putout#122]
file: `plugin-apply-destructuring/lib/apply-array-destructuring/index.js`

code: `    '__a = __b[1]': '[, __a] = __b',`

```
[, Item ] = [123];
 ^

SyntaxError: Unexpected token ','
```

wish:

```js

let DESTRUCTURING_PLACEHOLDER = null;

code: `    '__a = __b[1]': '[DESTRUCTURING_PLACEHOLDER , __a] = __b',`
```

**Comment by coderaiser** [comment]
```js
[, Item ] = [123];
```

Is correct [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). Could you please provide more details?
