### ISSUE TITLE
Node imports for TextEncoder and TextDecoder

### ISSUE THREAD

**Issue by epreston** [coderaiser/putout#123]
When using this amazing tool on javascript for the web, it includes the imports TextEncoder and TextDecoder as if I was building for node.js

import { TextEncoder } from 'util';
import { TextDecoder } from 'util';

Am I doing something wrong ?  How might i avoid this ?

**Comment by coderaiser** [comment]
It's related to [`declare`](https://github.com/coderaiser/putout/tree/master/packages/plugin-nodejs#declare) rule of `@putout/plugin-nodejs`. It is based on [@putout/operator-declare](https://github.com/coderaiser/putout/tree/master/packages/operator-declare#putoutoperator-declare-) and adds imports of Node.js globals.

To ignore some kind of globals use `dismiss` option:

```json
{
    "rules": {
        "nodejs/declare": ["on", {
            "dismiss": [
                "TextEncoder",
                "TextDecoder"
            ]
        }]
    }
}
```

Is it works for you?

**Comment by epreston** [comment]
Thank you, that works well. Happy holidays.
