### ISSUE TITLE
Rule extract-sequence-expressions fixes can be incorrect

### ISSUE THREAD

**Issue by epreston** [coderaiser/putout#124]
The rule: `extract-sequence-expressions`

Often has issues fixing sequence expressions that include extra parenthesis or function calls.  
I does well to identify the issues, but fails in fixing them.  For example:

> Example:
     `localStorage.setItem('country_code', s),`
     `(global.$stores.useCookieConsent = !t.includes(s));`

This will produce the output below

> Bad Output:
`localStorage.setItem('country_code', s, (global.$stores.useCookieConsent = !t.includes(s)));`

It should produce the following output.

> Expected Output:
    `localStorage.setItem('country_code', s);`
    `global.$stores.useCookieConsent = !t.includes(s);`

**Comment by coderaiser** [comment]
This case of [`@putout/plugin-extract-sequence-expressions`](https://github.com/coderaiser/putout/tree/master/packages/plugin-extract-sequence-expressions#putoutplugin-extract-sequence-expressions-) made by design, so:

```js
fn(a), 'hello';
```

Becomes:

```js
fn(a, 'hello');
```

Anyways your example contains [`AssignmentExpression`](https://babeljs.io/docs/en/babel-types#assignmentexpression) and it almost never should be parameter of a function call, so it's a good catch!

**Comment by epreston** [comment]
I feel these powerful code transformations could be mostly safe if the edge cases are addressed.

**Comment by epreston** [comment]
Another case for rule: `extract-sequence-expressions`

Two method calls in a sequence expression.

> Example:
    `this.process(), this.update();`

This will produce the output below

> Bad Output:
    `this.process(this.update());`

It should produce the following output.

> Expected Output:
    `this.process();` 
    `this.update();`

This happens in the simplest case.  From my tests today, it does not happen when proceeded by a `for` expression or when wrapped by `return` statement.  For example:

`return objtype.release(this), this;`

Will be correctly transformed to:

`objtype.release(this);`
`return this;`

**Comment by epreston** [comment]
It appears this only happens when there is 2 statements in the sequence. 3 statements work just fine. 

> Works as Expected
`this.process(), this.update(), this.render();`

Maybe the rule should be to combine (coalesce) function call and (literal / label).

**Comment by coderaiser** [comment]
> Maybe the rule should be to combine (coalesce) function call and (literal / label).

Sounds good! Are you up for a PR?

**Comment by epreston** [comment]
I hope to soon.  Right now, I can carefully test putout over a large code base.

**Comment by epreston** [comment]
Another case for `extract-sequence-expressions`

This rule does not see two method calls in a sequence expression when the right side is an `async` function call using `await`.

    > Example:
    `this.left('test'), await this.right();`

It should produce the following output.

    > Expected Output:
    `this.left('test');`
    `await this.right();`

**Comment by coderaiser** [comment]
Just lander ability to convert sequence call expressions in `@putout/plugin-extract-sequence-expressions@3.3.0`.

With `await` is a bit harder, since it’s ignored on traverse step, but not to much :).

**Comment by epreston** [comment]
I have a test case where `extract-sequence-expressions` fails to write out the right hand side of a code block.  **Effectively DELETING the code.**  I meant to write it up earlier.

Two of the same method calls, with different parameters. 

> Test Case:
```
function nodelete(txt, obj) {
  console.log(txt);
  console.log(obj);
}

nodelete('one', {
  test: 'somevalue',
}),
  nodelete('two', {
    foo: true,
    bar: 600,
    baz: 500,
  });
```

The second call to "nodelete" gets deleted.

> Bad Output:
```
function nodelete(txt, obj) {
  console.log(txt);
  console.log(obj);
}

nodelete('one', {
  test: 'somevalue',
});
```

We don't want the second call to be deleted / failed to be written out after transformation.

> Expected Output:
```
function nodelete(txt, obj) {
  console.log(txt);
  console.log(obj);
}

nodelete('one', {
  test: 'somevalue',
});
nodelete('two', {
  foo: true,
  bar: 600,
  baz: 500,
});
```

**Comment by epreston** [comment]
Another issue with code being **deleted or failing to write out**.  `extract-sequence-expressions`  does not like function names that use the _  (underscore) character. This is popular in a few libraries like lodash.

> Test Case:
`_(), foo.bar.baz(false);`

This will produce the output below, deleting the right hand side, our second method call in the sequence of expressions.

> Bad Output:
`_();`

It should produce the following output.

> Expected Output:
`_();`
`foo.bar.baz(false);`

**Comment by coderaiser** [comment]
I cannot reproduce the `nodelete` and `_` cases. Could you please re-install 🐊**Putout** with:

```js
npm i putout
```

And try again. Is it works for you now?
The case with `await` should work as well :).

**Comment by epreston** [comment]
The 3.4 update to the rule fixed both issues with missing code.  Solid work.

**Comment by coderaiser** [comment]
Nice! I closes this issue, feel free to create a new one :).
