### ISSUE TITLE
Idea: extend capability of `extract-sequence-expressions` or applicable rule

### ISSUE THREAD

**Issue by epreston** [coderaiser/putout#126]
One class of sequence expressions missed by the `extract-sequence-expressions` rule (or some other rule for this purpose) is when the sequence statements are tucked into an "if expression'.  For example:

```js
let a = true;

if(console.log('one'), console.log('two'), a) {
  console.log('three')
}
``` 

This is equivalent and more clearly written as:

```js
let a = true;

console.log('one');
console.log('two');

if (a) {
  console.log('three')
}
```

Javascript returns the last expression in the sequence for evaluation in the "if expression".

**Comment by epreston** [comment]
The issue with leaving these undetected is that it causes another rule, `remove-unused-variables`, to incorrectly determine that a variable is unused.  For example, "a" will incorrectly be matched as unused but it is used as the condition of the first "if statement".

```
let a = true;
let b = false;

if ((console.log('one'), console.log('two'), a)) {
  console.log('three');

  b = true;

  if (b) {
    console.log('four');
  }
}
```

**Comment by coderaiser** [comment]
Just landed support of `SequenceExpressions` to `@putout/plugin-remove-unused-variables` `v4.2.0`. Is it works for you?

**Comment by epreston** [comment]
Can confirm that `plugin-remove-unused-variables` now correctly detects the usage of a variable when: 
 - it is the evaluated as the condition of an if statement at the end of a sequence expression.

This is the edge case where some control statements, "if statements" in this case, will evaluate the last expression in a sequence as its condition.  Little known but valid javascript.

To answer your question: Older Vue 2 templates promoted a style of javascript that required a factory pattern that leads to these hard to spot issues.  It looks like an "if statement" with a complicated expression, but, its actually one or two simple statements, comma separated in a sequence, with trailing expression for the "if statement" to evaluate.  Over a a large project this created 80+ false flags for unused variables.

**Comment by epreston** [comment]
You are right about "left" associating single line control statements where the `BodyBlock` is optional.  If there is no block, one will have to be made.  "for, while, if" maybe others will use the following statement as its body without a `BodyBlock`.

I'd be excited to see if we can hoist out these sequence expressions.  Helpful if someone puts a comma in the wrong place creating a sequence expression when they mean to combine a condition into a larger expression for the control block.  It would be neat to hit save and see the statement get ejected above on its own line.

**Comment by coderaiser** [comment]
OK, it can be something like [this](https://putout.cloudcmd.io/#/gist/31ab1ee4f6dcef90706249da34192397/f6e50b2993aeaa47af1b3136e67ce2f4d8a8bd00), but I think about more cases that can be counted (`while`, `for`, `for-of`, `for-in`, `switch`... did I miss something?).

You can make a [🐊**Putout** plugin](https://github.com/coderaiser/putout#-plugins-api) from this draft, and install it separately. There is a [yoman generator](https://github.com/putoutjs/generator-putout) for this purpose that simplifies things a lot :).

**Comment by coderaiser** [comment]
Well, about loops, it changes behavior of code, so can be skipped, what statements besides `if` do you think should be supported?

**Comment by coderaiser** [comment]
> I'd be excited to see if we can hoist out these sequence expressions. Helpful if someone puts a comma in the wrong place creating a sequence expression when they mean to combine a condition into a larger expression for the control block. It would be neat to hit save and see the statement get ejected above on its own line.

Landed in `@putout/plugin-extract-sequence-expressions@3.5.0` 🎉. Is it works for you?

**Comment by epreston** [comment]
It works well. 

I'm going to write out some detailed bits so we have a good record of test overage, environment, versions.

## Tested Versions

| module                                      | version  |
| :------------------------------------------ | :------- |
| putout                                      | "28.3.0" |
| @putout/plugin-extract-sequence-expressions | "3.5.0"  |
| @putout/plugin-logical-expressions          | "1.2.0"  |

## Test Project Metrics

| language   | files |   code | comment | blank |  total |
| :--------- | ----: | -----: | ------: | ----: | -----: |
| JavaScript |   283 | 50,763 |   2,617 | 6,566 | 59,946 |

## Test Detection

94 errors in 50 files

## Test Detail

### Test 1:

- It hoists the sequence expressions found in 'if statements" correctly
- this is the simple case found above

### Test 2:

- When it is proceeded by a single line, left associating control statement with an optional `BodyBlock`
- It creates a `BodyBlock` if required, then hoists the sequence statements above leaving the condition
- preserves execution order and practical outcomes
- exposes the actual execution of the code by the runtime while improving readability

"For Statement" example for clarity:

```js
for (let n = 0; n < t.length; n++)
  if (((i = '(' + e + ': ' + t[n] + ')'), window.matchMedia(i).matches)) return t[n];
```

Is transformed into the more readable equivalent:

```js
for (let n = 0; n < t.length; n++) {
  i = '(' + e + ': ' + t[n] + ')';
  if (window.matchMedia(i).matches) return t[n];
}
```
