### ISSUE TITLE
Add support to visit function declarations in PutoutScript?

### ISSUE THREAD

**Issue by wenq1** [coderaiser/putout#132]
Any plan to support function declaration visitings in the script?

e.g.

```js
class A extends B {
    static async function test () {
         // todo support this?
    }

    async function test2 () {
         // todo support this?
    }
}
```

**Comment by coderaiser** [comment]
Is it valid JavaScript?

<img width="482" alt="image" src="https://user-images.githubusercontent.com/1573141/219104956-bcd5c7fb-d9d6-4053-97b4-cb0ea132d6fd.png">

**Comment by coderaiser** [comment]
If you just want manipulate with `FunctionDeclaration` you can set empty body, it will be enaugh:

```js
export const replace = () => ({
    'async function __a(__args) {}': (vars, path) => {
        path.node.async = false;
        return path;
    }
});
```

[Here is example](https://putout.cloudcmd.io/#/gist/55faa1fab71560646909a30d2e781df2/588189d35417a905c6ab43be2545c07f924d62fc).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
