### ISSUE TITLE
Bug for ESM module in plugin-package-json

### ISSUE THREAD

**Issue by HonzaMac** [coderaiser/putout#136]
After applying `plugin-package-json` rule make `package.json` syntactically incorrect.

Rule add this: 
```
{
  "name": "@project/common",
  "version": "1.0",
  'type': 'commonjs',
  "private": true,
...
```
Problem are single quotes, but double quotes should be present.

## How to reproduce?

1. `npx putout --fix common/`
2. Check package.json content
3. I see `'type': 'commonjs'`
4. I expected `"type": "commonjs"`

I apologise if this is not a bug - this is mine first usage of 🐊putout.

**Comment by coderaiser** [comment]
This is not a bug, the thing is you need to use 🐊**Putout** with **ESLint** plugin. 🐊**Putout does transformations, and **ESLint** does all formatting stuff.

**Comment by HonzaMac** [comment]
Thank you for help. 

I have tried to register eslint plugin as suggested. 

When I ran putout once more it again produced wrong syntax. I tried to run `eslint` with added plugin and safe rules and it failed on this: 

```
> eslint --cache --cache-location node_modules/.cache/web/.eslintCache/ --max-warnings 0 --ext .js,.ts,.tsx,.jsx .

Oops! Something went wrong! :(

ESLint: 8.37.0

SyntaxError: Cannot read config file: /web/common/eslint/unicorn-recommended.js
Error: Error parsing /web/common/package.json: Unexpected token ' in JSON at position 60
Referenced from: /web/.eslintrc.js
```

Seems eslint can't fix it until I fix it manually.

**Comment by coderaiser** [comment]
No need to run `eslint` just create `.eslintrc.json`:

```json
{
    "extends": ["plugin:putout/safe"],
    "plugins": ["putout"]
}
```

🐊**Putout** will see config, run ESLint which reads config and applies changes.

Is it works for you?

**Comment by coderaiser** [comment]
Just landed first class JSON support to 🐊**Putout** with [@putout/printer v4](https://github.com/putoutjs/printer/releases/tag/v4.1.0), from now no ESLint needed for this purpose :).

**Comment by HonzaMac** [comment]
I can confirm, that problem was solved and I no longer get error about package.json. 
Thank you
