### ISSUE TITLE
Package: conditions/convert-equal-to-strict-equal - Comparisons to null not safe to transform

### ISSUE THREAD

**Issue by epreston** [coderaiser/putout#139]
Package: conditions/convert-equal-to-strict-equal
Issue: Comparisons to null not safe to transform

Example:

```js
if (test != null) {
  // do something
}
```

This is not safe to transform into strict compare with `!==` when `null` is the right hand side of the expression.  Often, the "loose equality comparison that performs type coercion if necessary" is desired to catch both null and undefined.

Detailed reference on the issue: https://stackoverflow.com/a/15992131/900263

--------

Update: 

Version: Version: 29.3

Description: yoda expressions are reversed but continue to be evaluated in the original order. This causes rule exclusions to be bypassed.

**Comment by epreston** [comment]
Almost, 11 more hours of testing.  So many new goodies.

**Comment by coderaiser** [comment]
Wait a minute, as I see this case already handled:

https://github.com/coderaiser/putout/blob/ac566372d30937a7dba1e9282dd013e4478034f8/packages/plugin-conditions/lib/convert-equal-to-strict-equal/index.js#L5-L13

**Comment by epreston** [comment]
I was getting conversions in 2 cases.  The normal one and when the operands reversed.

- `test != null`
- `null != test`

Will update with test cases.

**Comment by epreston** [comment]
I may have started with `null != test` that got corrected to `test != null` but then the transform was applied.

**Comment by coderaiser** [comment]
[`yoda`](https://eslint.org/docs/latest/rules/yoda) rule of ESLint can help you with this.

**Comment by epreston** [comment]
Confirmed, I had statements like `null != test` that got reversed then snuck through.

**Comment by epreston** [comment]
Retesting for 29.4.0 update

**Comment by coderaiser** [comment]
> Retesting for 29.4.0 update

What purpose of this retest? I don't think it will be fixed if you don't send PR.

**Comment by epreston** [comment]
Oh.. ok.  This is just a quick note to say that I'm not leaving old issues open from previous versions.  
I'll get to work on it.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝. Fee free to reopen when you have chance to work on this.
