### ISSUE TITLE
Default export to name export

### ISSUE THREAD

**Issue by killerdejavu** [coderaiser/putout#143]
Wanted some help on how to write a transformation which would be able to help with something like this? 

From:

```js
const x = () => {}
const y = () => {}
export default { x, y }
```

To: 

```js
export const x = () => {}
export const y = () => {}
```

We are trying to move from commonJS to module exports, and most of our commonjs exports are like this

```js
module.exports = {
  a,
  b,
}
```

**Comment by coderaiser** [comment]
As I understand what you want is have ability to use imports this way:

```js
import {x, y} from 'your-module';
```

Instead of

```js
import yourModule from 'your-module';
```

Is it correct?

The simplest possible way would be:

```js
export const report = () => `Use 'ExportNamedDeclaration' instead of 'ExportDefaultDeclaration'`;

export const fix = (path) => {
    path.node.type = 'ExportNamedDeclaration';
};

export const include = () => [
    'ExportDefaultDeclaration',
]
```

Checkout in 🐊[**Putout Editor**](https://putout.cloudcmd.io/#/gist/6ac75a03d745d8c1992dbb6854e40257/98996d1a39669b12866edf74654110b30671782b).

**Comment by coderaiser** [comment]
Here is more sophisticated example:

```js
// https://git.io/JqcMn

export const report = () => `Use 'ExportNamedDeclaration' instead of 'ExportDefaultDeclaration'`;

export const fix = (path) => {
    for (const prop of path.get('declaration.properties')) {
        const {name} = prop.node.key;
        const current = path.scope.bindings[name].path.parentPath;
        
        current.replaceWith(ExportNamedDeclaration(current.node));
    }
    
    remove(path);
};

export const include = () => [
    'ExportDefaultDeclaration',
];
```

Check out in 🐊[**Putout Editor**](https://putout.cloudcmd.io/#/gist/a6d1f955837688d2d85781f9219581f7/b0305c6e420c10d9056c181c563a51cbdf564a25)

**Comment by coderaiser** [comment]
Is it works for you?

**Comment by so1ve** [comment]
Hmmm. I don't think this transform is 100% secure because we can use default import in the first form but we need to use an "import star" in the second form.

**Comment by coderaiser** [comment]
So first form is works for you?
