### ISSUE TITLE
Online editor does not preserver grouping.

### ISSUE THREAD

**Issue by kamoser** [coderaiser/putout#146]
Not sure if I'm missing something here, but when trying out the [online editor](https://putout.cloudcmd.io/) with some basic Math replacers, or even no operations, parentheses grouping is not preserved. For example, the input `2 * (2 + 1)` (or `Math.imul(2, 2 + 1)` with the script `export const replace = () => ({'Math.imul(__a, __b)': '__a * __b'});`) produces  `2 * 2 + 1`. Evaluation in console or parsing with just acorn/recast on [AST Explorer](https://astexplorer.net/) will produce the correct result of `2 * (2 + 1)`.

This does not happen when installing as an npm package locally, as it produces the correct `2 * (2 + 1)` result from the built in apply-multiplication rule (which seems to just be the same `export const replace = () => ({'Math.imul(__a, __b)': '__a * __b'});`). Also, trying `2 * (2 + 1)`  on [AST Explorer](https://astexplorer.net/) will also produce the correct result of `2 * (2 + 1)`.

**Comment by coderaiser** [comment]
Thank you! Fixed with https://github.com/putoutjs/printer/commit/a7f4de318454cfe30be5e015e320cddd824bc149. Landed in [`@putout/printer@1.99`](https://github.com/putoutjs/printer/releases/tag/v1.99.0) 🎉.

Just updated 🐊**Putout Editor**. Is it works for you?

**Comment by kamoser** [comment]
Awesome, just tested works great!
