### ISSUE TITLE
`--fix` breaks type generics

### ISSUE THREAD

**Issue by atmin** [coderaiser/putout#147]
Minimal example:

```js
✗ npx putout --version
v30.4.1

✗ cat test.ts
export default function test(map: Map<string, unknown>) {
  console.log('putout');
  map.set('test', 42);
}

✗ npx putout test.ts
test.ts
 2:2  error   Avoid 'console' call  remove-console

✖ 1 errors in 1 files
  fixable with the `--fix` option

✗ npx putout test.ts --fix

✗ cat test.ts
export default function test(map: Map<stringunknown>) {
    map.set('test', 42);
}
```

It replaces ", " with "" pretty consistently in all type arguments. Another observation (on code I cannot share) is it does not respect formatting applied by Prettier.

**Comment by coderaiser** [comment]
Thanks, fixed in `@putout/printer` [v2.71.0](https://github.com/putoutjs/printer/releases/tag/v2.71.0). Please re-install 🐊**Putout**, is it works for you?

**Comment by coderaiser** [comment]
> Another observation (on code I cannot share) is it does not respect formatting applied by Prettier.

[`@putout/printer`](https://github.com/putoutjs/printer/) (which is used by default starting from [v30](https://github.com/coderaiser/putout/releases/tag/v30.0.0)) is opinionated printer, it not tries to guess how formatting should look like (like `recast` does), and works twice faster.

It definitely produce different resalt then `prittier`, but you can run `prittier` after 🐊**Putout** to achieve formatting you want.

If you for some reason want to get back to old behavior use `recast` as `printer` in your `.putout.json`:

```json
{
    "printer": "recast"
}
```

There is also [ESLint plugin](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#readme) so you can use both 🐊**Putout** and `prittier`.

**Comment by atmin** [comment]
Awesome, this example works correctly now.

Cool with your choice to use the faster formatter by default.

I noticed other issues. I agree with **🐊Putout** assessment of code smells, I find it valuable as a reporter. But after using `--fix` on non-basic TypeScript types, I get TS errors as a result.

These are different issues, though, and need proper description. Closing this one.

**Comment by coderaiser** [comment]
> But after using --fix on non-basic TypeScript types, I get TS errors as a result.

Would be awesome if you provide me some examples, so I can improve `@putout/printer`, it has very simple API, based on a simple conceptions, where you have:
- ✅ `write(str)`
- ✅ `traverse(node)`
- ✅ `print(str | node) = write(str) || traverse(node)`
- ✅ `indent()`
- ✅ `newline()`
- ✅ `breakline()` = `newline() + indent()`
- ✅ `linebreak()` = `indent()  + newline()`

That is what used in all node visitors. The simplest visitor is:

```js
function DebuggerStatement(path, {write}) {
    write(‘debugger’);
}
```

It’s easily extendable and supports any type of JavaScript extension to be build on top of it.
