### ISSUE TITLE
`remove-useless-spread/array` is over-zealous

### ISSUE THREAD

**Issue by atmin** [coderaiser/putout#148]
```js
✗ cat test.ts
export default function () {
    const map = new Map();
    map.set('a', 1);
    map.set('b', 2);
    return [...map.values()].sort((a, b) => a[1] - b[1]);
}

✗ npx putout test.ts
test.ts
 5:11  error   Avoid useless spread '...'  remove-useless-spread/array

✗ npx putout test.ts --fix

✗ cat test.ts
export default function () {
    const map = new Map();
    map.set('a', 1);
    map.set('b', 2);
    return map
        .values()
        .sort((a, b) => a[1] - b[1]);
}
```

The problem is `map.values()` returns an iterator, so a copy is necessary to use array methods. Otherwise, calling the `--fix`ed function returns `Uncaught TypeError: map.values().sort is not a function`.

Another example, `[...document.querySelectorAll('a')].map(console.log)`.

**Comment by coderaiser** [comment]
Better to use `Array.from()` in such cases, since spread could be left accidentally like with `[…Object.values(c)]`, or you can disable this rule if you prefer such way of converting.

**Comment by atmin** [comment]
That's reasonable.

But I'd expect `--fix` to not break working code. It's fine to replace the spread with `Array.from`, or not replace it, at all.

**Comment by coderaiser** [comment]
Fixed in https://github.com/coderaiser/putout/commit/faec6bbc628c8f7cceec864be91717911c06238b 🎉 . Pleas re-install 🐊**Putout**. Is it works for you?

**Comment by atmin** [comment]
Thanks, it works now 👍
