### ISSUE TITLE
[eslint-plugin-putout]: remove-unused-variables deletes type definitions for `this` context

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#150]
In TypeScript you have the option to type the this context inside a function. This type definition is the first parameter inside a function.

For example:

```ts
const f = (a, b) => a + b + this.c // this is type of any
f.c = 5
```

```ts
const f = (this: { (a, b): number, c: number }, a: number, b: number) => {
  return a + b + this.c // this is type of  { (a, b): number, c: number }
}
f.c = 5
```

The problem is that the rule `remove-unused-variables` also removes the type definition of `this`.

**Comment by coderaiser** [comment]
I'm not sure I understand code example, [typescript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZjAvDAFFAFgSwgLhgb1QEMAaGAIwEo8wBXAW3IFMAnM4Gh5lmAXzKKdGrMuSHdKSAHwEAUDBgsmUWizAwiMANQVtMDNgB0wGAHpT+rBBjZ9ATwAOTGCAQFio6jDrC2MDt5crHyyvLJwxkgwAKyyskA) shows me:

<img width="292" alt="image" src="https://github.com/coderaiser/putout/assets/1573141/a3c4e17e-3490-4d73-b900-2f219d4dae93">

And [Babel](https://putout.cloudcmd.io/#/gist/ce57c39cfc4233283c7cd4a85ca70131/655445728e0353f224553dc9bd7ff412b96b16b6):


<img width="294" alt="image" src="https://github.com/coderaiser/putout/assets/1573141/38e4a193-f4ad-4a0f-9575-30bea8b258d2">

**Comment by coderaiser** [comment]
I can't reproduces any issues, I have such result:

```ts
const f = function(this: {
    (a: number): number;
    c: number;
}, a: number, b: number) {
    return a + b + this.c; // this is type of  { (a, b): number, c: number }
};

f.c = 5;
```

**Comment by coderaiser** [comment]
Cannot reproduce, please re-open if have more details
