### ISSUE TITLE
[plugin-remove-console]: Removes any kind of `console` function and not only `console.log`

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#151]
While I like the idea of removing `console.log`, It's a bit to much to also remove `console.error` or `console.warn` for logging or error utilities. It would be better to update the README and/or to add configurations to remove only specific kinds of console commands, such as:

```json
{
    "rules": {
        "remove-console": ["on", {
            "log": true,
            "warn": false,
            "error": false
        }]
    }
}
```

**Comment by coderaiser** [comment]
That's a nice idea! You can configure it right now in a way you like using 🦎[**Putout Script**](https://github.com/coderaiser/putout/blob/master/docs/putout-script.md#-putoutscript)

```js
{
    "rules": {
        "remove-console": ["on", {
            "exclude": [
                "console.warn(__args)",
                "console.error(__args)"
            ]
        }]
    }
}
```

**Comment by ElPrudi** [comment]
Surprisingly enough, it does work. Thank you very much :)

Still, it would be nice to include it in the readme. It's a very good selling point, because eslints `no-console` has no configuration. And I'm sure I'm not the only one with this problem.

**Comment by coderaiser** [comment]
[`exclude`](https://github.com/coderaiser/putout#exclude) works for all plugins :).
