### ISSUE TITLE
[types/convert-typeof-to-is-type]: Rule does not check for `typeof x === 'bigint'`

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#158]
I like the concept of the rule to keep my bundle size short, but I think you accidentally forgot to include the `bigint` type. To be fair, I guess it's a rather new addition to JS.

```ts
const isBigInt = (value) => typeof value === 'bigint'
```

**Comment by coderaiser** [comment]
Nice idea :)!

Just updated `@putout/plugin-types` 🎉 . Please re-install 🐊**Putout**. Is it works for you?

**Comment by ElPrudi** [comment]
Yes, it's working. Thank you very much :)
