### ISSUE TITLE
[convert-array-copy-to-slice]: Wrongly triggers by `Map` and `Set` conversion

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#160]
In JavaScript there is a quite unconventional, but incredibly fast way to convert Maps and Sets to Array, as seen here:

```ts
const map = new Map()
map.set('a', 0)
map.set('b', 1)

console.log([...map]) // [[ 'a', 0 ] [ 'b', 1 ]]

const set = new Set(['a', 'a', 'b'])

console.log([...set]) // ['a', 'b']
```

The problem is, that this rule reads this syntax as typical array syntax and tries to convert it to functions both `Map` and `Set` don't have.

**Comment by coderaiser** [comment]
You can disable this rule, or use:

```js
console.log(Array.from(map))
```

The thing is sometimes `...` used in places where it was accidentally forgotten, like this one:

```js
function(a = [], b = []) {
    return [
       ...a,
       ...b,
    ];
}
```

Then `b` was dropped since there is no need for it:

```js
function(a) {
    return [
       ...a,
    ];
}
```

And only `a` is left. What type of `a`? What purpose of this `spread`? Is it just copy, or convert, or copy + convert?

**Comment by ElPrudi** [comment]
Since I'm writing a lot of atomic utilities, the performance has the be priority, so I can't use `Array.from`. I'm gonna deactivate this rule for these utilities and just move on. Thank you anyway :)

**Comment by coderaiser** [comment]
We can create a new plugin that will do things for optimization for speed, so it will change:

- `Boolean(__a)` -> `!!a`;
- `Array.from(__a)` -> `[...__a]`

**Comment by ElPrudi** [comment]
That's actually a great and much needed idea. Give me some time and I open a new issue with some ideas later.

**Comment by coderaiser** [comment]
This rules feats good to [`minify/types`](https://github.com/coderaiser/putout/blob/master/packages/plugin-minify/lib/types/index.js), by the way :).
