### ISSUE TITLE
[conditions/remove-zero]: Cases with inlined increments and decrements are incorrectly fixed.

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#161]
There is a way where you can transform this:

```ts
const x = 1
--x
if (x === 0) console.log("hello")  // -> outputs "hello"
```

to this:

```ts
const x = 1
if (--x === 0) console.log("hello") // -> outputs "hello"
```

But this rule only removes the `=== 0`, but doesn't negate the operation:

```ts
// after [conditions/remove-zero]
const x = 1
if (--x) console.log("hello") // -> does not output "hello"
```

It should actually autofix to this:

```ts
const x = 1
if (!--x) console.log("hello")
```

The same thing goes for `++x`.

**Comment by coderaiser** [comment]
I can't reproduce this, is a bug still occurs?

**Comment by coderaiser** [comment]
Not quite understand what is the way to convert:

```js
const x = 1
--x
if (x === 0) console.log("hello") 
```

to:

```js
const x = 1
if (--x) console.log("hello")
```

Do you have such transform?

**Comment by ElPrudi** [comment]
I guess the error is bit more complex than expected. Its more like this:

```ts
export default class X {
   private count = 0
   private stuff: Record<string, any> = {}

   add(x): void {
       this.count++
       this.stuff[x.toString()] = x
   }

  clear(x): void {
     if (--this.count === 0) {
        this.stuff = {}
     } else {
         delete this.stuff[x.toString()]
  }
}
```

If you want a real world example, I got this idea from [eventemitter3](https://www.npmjs.com/package/eventemitter3)

**Comment by coderaiser** [comment]
Looks like it's related to https://github.com/coderaiser/putout/issues/157

**Comment by coderaiser** [comment]
```diff
const x = 1
---x
-if (x === 0) console.log("hello") 
+if (--x === 0) console.log("hello") 
```

🐊[**Putout Editor**](https://putout.cloudcmd.io/#/gist/1b0ad2900f604352697e8edc9f2be61b/a966a7971721dc19665837af20352a6165bb9a24)

**Comment by ElPrudi** [comment]
Thank you, but this wasn't the issue.

> I guess the bug is a bit more complex than expected. Its more like this:
> 
> ```ts
> export default class X {
>    private count = 0
>    private stuff: Record<string, any> = {}
> 
>    add(x): void {
>        this.count++
>        this.stuff[x.toString()] = x
>    }
> 
>   clear(x): void {
>      if (--this.count === 0) {
>         this.stuff = {}
>      } else {
>          delete this.stuff[x.toString()]
>   }
> }
> ```
> 
> If you want a real world example, I got this idea from [eventemitter3](https://www.npmjs.com/package/eventemitter3)

From this example, the `clear` function gets fixed incorrectly to:

```ts
clear(x): void {
    if (--this.count) {
        this.stuff = {}
    } else {
       delete this.stuff[x.toString()]
    }
}
```

Which means, that the logic gets inverted.

**Comment by ElPrudi** [comment]
Your editor doesn't understand TypeScript.

**Comment by coderaiser** [comment]
> Your editor doesn't understand TypeScript.

![image](https://github.com/coderaiser/putout/assets/1573141/5f9f18d0-92fd-43c1-8763-bb1b118864a0)

You can enable it in Babel settings.
