### ISSUE TITLE
[math/apply-exponentiation]: Ignore `x * x`

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#163]
This rule should ignore cases like `x * x` or `x * x * x` as these are strong mathematical optimizations. Please do not include this in your rule or create a separate rule. I like the fact that it's replacing `Math.pow`, but not, that it makes my mathematical algorithms slower.

**Comment by coderaiser** [comment]
You can exclude expressions you don't need to be touched, just update your `.putout.json` with:

```json
{
    "rules": {
        "math/apply-exponentiation": ["on", {
            "exclude": [
                "__a * __a"
            ]
        }]
    }
}
```

Is it works for you?

**Comment by ElPrudi** [comment]
Yes, it did work, after writing:
```json
{
    "rules": {
        "math/apply-exponentiation": ["on", {
		"exclude": [
			"__a * __a",
			"__a * __a * __a",
			"__a * __a * __a * __a",
			"__a * __a * __a * __a * __a",
		]
	}]
    }
}
```

But you update your README.md to better explain `exclude`. I didn't even know that `__a` was supposed to be the internal syntax for a variable.

**Comment by coderaiser** [comment]
This is 🦎[PutoutScript](https://github.com/coderaiser/putout/blob/master/docs/putout-script.md). You can improve documentation and code in any way :)

**Comment by ElPrudi** [comment]
Ah, my bad. Thank you anyway.
