### ISSUE TITLE
[types/convert-typeof-to-is-type]: `typeof` commands used in assignments are not detected.

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#166]
While it does works wonderfully inside conditions, if you outsource this check to reuse it later, these assignments are not checked.

```ts
let x = 0
if (typeof x === 'number') x++ // eslint issue!
if (typeof x === 'number') x++ // eslint issue!
if (typeof x === 'number') x++ // eslint issue!
```

```ts
let x: number | number[] = 0
const isNum = typeof x === 'number' // no eslint issue
if (isNum) x++
if (isNum) x++
if (isNum) x++
```

TypeScript is already smart enough to understand that this guard is active, so it doesn't output any errors.

**Comment by coderaiser** [comment]
I cannot reproduce this, I have:

```js
const isNumber = (a) => typeof a === 'number';
let x = 0;

if (isNumber(x))
    x++;

if (isNumber(x))
    x++;

if (isNumber(x))
    x++;
```

**Comment by coderaiser** [comment]
There is a check, that parent is not `VariableDeclarator`, so that's by design:

https://github.com/coderaiser/putout/blob/29b258759bb2cc60fbf5a06df2f3446b925e4981/packages/plugin-types/lib/convert-typeof-to-is-type/index.js#L62-L67

Do you want result was something like this?

```ts
const isNumber = (a) => typeof a === 'number';
let x: number | number[] = 0
const isNum = isNumber(x);

if (isNum) x++
```

**Comment by ElPrudi** [comment]
Yes, the code example you've shown is exactly what I need.

**Comment by coderaiser** [comment]
Ok! That's possible, just landed 🎈 . Is it works for you?

**Comment by ElPrudi** [comment]
Yes, it does work. Thank you very much :)
