### ISSUE TITLE
[printer] Removes any `declare` of class properties.

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#175]
If you want to do more complex polymorphism in TypeScript, there's a problem when it comes to instance properties: you can't change their inherited type. But if the subclasses fully manage this type and it mostly completely overlaps with the type of the properties in the parent class, TypeScript lets you `declare` the type again:

```ts
export default class SuperTest extends Test {
    protected declare title: string[] // change the type of title from string to string[], because why not?
}
```

After transformation, it looks like this:

```ts
export default class SuperTest extends Test {
    protected title: string[]  // Error! Can not redeclare an inherited property!
}
```

**Comment by coderaiser** [comment]
**TypeScript** has so many abilities 😀... Just fixed 🎈! Is it works for you?

**Comment by ElPrudi** [comment]
It doesn't try to change it anymore. Thank you very much :)
