### ISSUE TITLE
[types/convert-typeof-to-is-type]: Does not fix `typeof a === 'object'`

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#178]
It seems you forgot another `typeof` type check to fix in this rule. This can be easily fixed in JS:

```js
const isObj = (a) => typeof a === 'object'
```

and TS:

```ts
const isObj = (a): a is Record<any, any> => typeof a === 'object'
```

**Comment by coderaiser** [comment]
That’s a good idea for a PR :)

**Comment by coderaiser** [comment]
This is absolutely same as in https://github.com/coderaiser/putout/issues/158: 
c23fa1e, dfc5954

**Comment by coderaiser** [comment]
@ElPrudi how do you think checking of type should look like?

https://github.com/coderaiser/putout/blob/9461e44d04fb7ec2f0e9cc7162301c64b7c6b9af/packages/plugin-types/lib/declare/index.js#L9

`types/declare` already supports `isObject()`, but we should remember that `typeof null === 'object'`, so check should be more sophisticated, and I’m not sure a lot people checks `object` type in a similar way, what do you think?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝 Feel free to reopen when you have new ideas.
