### ISSUE TITLE
question: how can I use putout to transform unicode regexes (/../u)?

### ISSUE THREAD

**Issue by retorquere** [coderaiser/putout#179]
I have to maintain code that is targeted both at environments that support unicode regexes as some that don't; it'd be great if I could use putout to rewrite the code towards plain regexp (not incredibly hard), but I have to find and parse the regexes themselves. If I can find the regexes, I could use https://www.npmjs.com/package/regexp-to-ast to parse them and return the rewritten ones.

**Comment by coderaiser** [comment]
Could you please provide code example: before and after?

**Comment by coderaiser** [comment]
One of the ways to transform regular expressions is using [Traverser](https://github.com/coderaiser/putout/tree/master/packages/engine-runner#traverser):

```js
export const report = () => `Remove regular expression`;

export const fix = (path) => {
    path.remove();
};

export const traverse = () => ({
    RegExpLiteral(path) {
        push(path);
    }
});
```


Check out in 🐊[Putout Editor](https://putout.cloudcmd.io/#/gist/5cd680e6bd64ee488d1be136c435ac47/b6e079c45ab8806a41b62e5ba1144d77783f6c36)

**Comment by retorquere** [comment]
I'm going to give this a try -- super thanks! This will make maintenance *much* easier.

**Comment by coderaiser** [comment]
I'll close it if all questions resolved, feel free to reopen if you have any questions :)
