### ISSUE TITLE
disable formatting

### ISSUE THREAD

**Issue by oprogramador** [coderaiser/putout#18]
I opened https://github.com/oprogramador/putout/pull/1 and I used the same `.putout.json` file but with `"remove-unused-variables": "on",`.

Generally it works fine, removing only unused variables bot for some JSX files it changed formatting.

e.g. it used to be:
```
export const Teams = props => (
  <>
    <header
```

it was changed to:
```
export const Teams = () => <>
  <header
```

**Comment by coderaiser** [comment]
Look, formatting is kept as similar to original as possible using [recast](https://github.com/benjamn/recast) library. To avoid any formatting issue you can use [eslint-plugin-putout](https://github.com/coderaiser/putout#eslint) which will handle most stuff for you :).
