### ISSUE TITLE
Getting error for apply-nullish-coalescing

### ISSUE THREAD

**Issue by faran-tenovos** [coderaiser/putout#182]
After updating to v2 of `apply-nullish-coalescing` I get the following error.
 I'm using `type module` in package.json

`Error: require() of ES Module /Some-user/node_modules/.pnpm/@putout+plugin-apply-nullish-coalescing@2.0.0_putout@31.8.4/node_modules/@putout/plugin-apply-nullish-coalescing/lib/apply-nullish-coalescing.js from /some-user/node_modules/.pnpm/putout@31.8.4/node_modules/putout/lib/putout.js not supported`

**Comment by coderaiser** [comment]
How do you use **Putout**?
From CLI, API or ESLint plugin?

**Comment by faran-tenovos** [comment]
I use it via ESLint

**Comment by coderaiser** [comment]
You can’t try to update your ESLint config with:

```json
{
    "extends": [
        "plugin:putout/esm"
    ],
    "plugins": [
        "putout"
    ]
}
```

Is it works for you?

**Comment by faran-tenovos** [comment]
I moved past forward that error but now I'm getting
`Error: Avoid 'use strict' in ESM (strict-mode/remove-useless)  putout/putout`
I'm using next.js and need to add 'use client' at top of the client-side components

**Comment by coderaiser** [comment]
Just fixed with `@putout/plugin-strict-mode v8`, please re-install 🐊**Putout**. Is it works for you?

**Comment by faran-tenovos** [comment]
@coderaiser it works now. Thanks for such quick support.
