### ISSUE TITLE
TypeScript type being removed in output when using object destructuring

### ISSUE THREAD

**Issue by incleaf** [coderaiser/putout#183]
<img width="1246" alt="image" src="https://github.com/coderaiser/putout/assets/7221609/d3f55ce6-710d-43b7-9ea1-96ec7aac842d">

[Here](https://putout.cloudcmd.io/#/gist/0dbc92a8f8646b31ab570f7fb3a5f3de/549182f4436b0f37bfbde7f2eaea2ad0a8621fcb)'s a snippet of reproducible codes

**Comment by coderaiser** [comment]
Thanks! Just landed support of `typeAnnotations` to `ObjectPattern` in [@putout/printer v5.2.0](https://github.com/putoutjs/printer/releases/tag/v5.2.0) 🎉 .

Please re-install 🐊**Putout**, is it works for you?
