### ISSUE TITLE
TypeScript union type as a key turns into extends expression

### ISSUE THREAD

**Issue by incleaf** [coderaiser/putout#185]
<img width="1192" alt="image" src="https://github.com/coderaiser/putout/assets/7221609/8982ec5f-2dea-436a-9d03-297abe67d808">

Here's a [snippet](https://putout.cloudcmd.io/#/gist/d6a36bc893caf6299fe7505a9a056cc9/24afbfad68d7984cb3882dc05092926b55e0019e) of it.

**Comment by coderaiser** [comment]
Thanks a lot, fixed with https://github.com/putoutjs/printer/commit/8e5d5f5015e8fedf80332674148ccbf4ccd4bf93, landed in [@putout/printer v5.22](https://github.com/putoutjs/printer/releases/tag/v5.22.0) 🎉. 
Please re-install **🐊Putout**

Is it works for you?

**Comment by incleaf** [comment]
@coderaiser It works! Thank you for your work.
