### ISSUE TITLE
TypeScript interface `extends` gets removed 

### ISSUE THREAD

**Issue by incleaf** [coderaiser/putout#186]
<img width="1124" alt="image" src="https://github.com/coderaiser/putout/assets/7221609/35dbe7d3-c301-4eda-b8cf-f0d35ad6404c">

Here's a [snippet](https://putout.cloudcmd.io/#/gist/1ce70fd480cb757b2707803fecdd9aef/fc7a487b5b2d9b1c8265d323af490d11c13b2ce8) of it

**Comment by coderaiser** [comment]
Thank you! Just fixed 🎉 , please re-install 🐊**Putout**, is it works for you?
