### ISSUE TITLE
Eslint Plugin Relying on Stylistic 

### ISSUE THREAD

**Issue by faran-tenovos** [coderaiser/putout#188]
@coderaiser The new version of putout-eslint plugin relies on stylistic which has not been released as a general release yet. Also major frameworks like nextjs are still relying on eslint and eslint typescript etc. I think the plugin should be used once the plugins are deprecated.

**Comment by coderaiser** [comment]
Is it produces any issues for you?

**Comment by faran-tenovos** [comment]
@coderaiser https://eslint.style/contribute/project-progress By this the plugins are still not deprecated and I've configured rules for the plugins above since they are being used by next.js and Updating to eslint-plugin-putout complains about those rules since it is using stylistic.

**Comment by coderaiser** [comment]
How it complains?

**Comment by faran-tenovos** [comment]
For instance, I'm using eslint-plugin-react and putting in my overriden rules like indent: 2, does not work because the plugin now complains as it is using stylistic. Same is the case with typescript-eslint which is being used next.js. While stylistic has other plugin

**Comment by coderaiser** [comment]
Look, it is deprecated https://typescript-eslint.io/rules/indent, so you better switch to stylistic, or just disable all stylistic rules provided by `eslint-plugin-putout`, or just use previous version (with [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json/#overrides) if it is nested dependency).

**Comment by coderaiser** [comment]
Is it works for you?
