### ISSUE TITLE
404 Page of Node v12 link in README.

### ISSUE THREAD

**Issue by niranjan-kurhade** [coderaiser/putout#189]
![image](https://github.com/coderaiser/putout/assets/97905637/a4e02cc1-1ca1-4876-91e4-314dfd2d24bd)

The above Screenshot has a node v12 link, which when clicked goes to a 404 page of Nodejs.

![image](https://github.com/coderaiser/putout/assets/97905637/9ee15e0b-0098-45ad-868b-0a6c2d80d264)

As we can see here.

Hence, the broken link needs to be fixed.

**Comment by niranjan-kurhade** [comment]
Please assign this issue to me. I would like to fix it. Also what version of node should be replaced with?

**Comment by coderaiser** [comment]
Thanks! Would be great if you change link to correct one to node v12 and information about ESM. Would be amazing if it will be of node.js official resource.

**Comment by niranjan-kurhade** [comment]
> node v12 and information about ESM

Hey @coderaiser Can you please check if this is the correct link - https://nodejs.org/en/blog/release/v12.3.0
