### ISSUE TITLE
remove unused variables keeping methods invokation

### ISSUE THREAD

**Issue by oprogramador** [coderaiser/putout#19]
Generally `remove-unused-variables` rule works correctly but sometimes there's a situation like:
```js
const result = await API.put(id, payload);
```
so we need to remove unused `const result = ` but keep `await API.put(id, payload);`.

This rule could accept some options:
- to always invoke functions/ methods and remove only assignments
- to detect in some way whether a function/ method modifies anything:
  - having knowledge about lodash methods
  - assuming that if a method name starts with `get` or `is` or `check`, it doesn't modify anything

**Comment by coderaiser** [comment]
Look, heuristic you talking about goes beyond `putout` and one of it's core plugins. I see no reason to support all possible libraries and parse it's names. Anyways you can fork `@putout/plugin-remove-unused-variables` and add anything you want :).
About removing only assignments that's a good idea for a PR :).
