### ISSUE TITLE
convert-commonjs-to-esm/exports not working

### ISSUE THREAD

**Issue by ngugcx** [coderaiser/putout#191]
.putout.json

```json
{
    "rules": {
        "strict-mode/add-missing": "off",
        "package-json/add-type": "off",
        "convert-commonjs-to-esm": "on",
        "remove-console": "off",
        "convert-commonjs-to-esm/require": "on",
        "convert-commonjs-to-esm/commons": "on",
        "convert-commonjs-to-esm/exports": "on",
        "try-catch/sync": "off"
    }
}
```

lib.js

```js
function test() {
    console.log('test');
}

exports.test = test;
```

`package.json`:

```json
{
    "name": "putout-test",
    "version": "1.0.0",
    "type": "module",
    "main": "index.js",
    "license": "MIT"
}
```

`putout lib.js --fix`

exports in lib.js is not modified.

```
putout -v
v32.16.0
```

**Comment by ngugcx** [comment]
`putout -v
v32.16.0
`

**Comment by coderaiser** [comment]
This is not really a good idea to use:

```js
exports.test = test;
```

Since:

```js
exports = test;
```

Will just overwrite `exports` variable, not make any exports.

**Comment by ngugcx** [comment]
One of third party modules I'm using now uses this way to export.
Can putout handle it?

**Comment by coderaiser** [comment]
Yes, just landed a new rule `[nodejs/convert-exports-to-module-exports`](https://github.com/coderaiser/putout/blob/d36d198f88db2932043d57626c0670f174e74393/packages/plugin-nodejs/README.md#convert-exports-to-module-exports). Enable it, and it will do the thing.

**Comment by coderaiser** [comment]
Upgrade to [v33](https://github.com/coderaiser/putout/releases/tag/v33.0.0) and try it, should work for you use case.

**Comment by ngugcx** [comment]
Tried, lots of plugin not found errors:
```
No plugin found for a rule: "convert-commonjs-to-esm"
No plugin found for a rule: "convert-commonjs-to-esm/require"
```

**Comment by coderaiser** [comment]
There is no more such plugins, read [release notes](https://github.com/coderaiser/putout/releases/tag/v33.0.0).
