### ISSUE TITLE
Question: Reverse mode

### ISSUE THREAD

**Issue by enzonotario** [coderaiser/putout#195]
Hi there!

Is there any way to run transformations in "reverse mode"? so that I can get the original code back from the transformed code.

Thanks!

**Comment by coderaiser** [comment]
There is no such a feature, anyways there is a couple ways you can achieve this:
- [use `git commit`](https://github.com/coderaiser/putout#-usage) to save your code before running 🐊**Putout** to see if applied changes is good for you, or you need to `got checkout —- .` and [disable some rules](https://github.com/coderaiser/putout#-what-is-rule).
- You can use [`eslint-plugin-putout`](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#readme) with **ESLint** or inside IDE of your choice, so [all dangerous rules](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#safe-mode) will be disabled.
- We can use (or develop, but I thin `git` is good enough for this purpose 🤔) some tool to save the state of your codebase.
- We can add a new flag `—-backup` to store backup in a temporary file in `node_modules` in the similar way [enabled by default cache works](https://github.com/coderaiser/putout/tree/master/packages/cli-cache#readme);

What option do you think would be the best?

**Comment by enzonotario** [comment]
Well, maybe I'm wrong but let me explain what I want to do:

I have a little project [EsJS](https://github.com/es-js/esjs) that wants to "extend" JavaScript with Spanish keywords. Of course, I saw your Goldstein project, but I want to try Putout without extending Acorn.

For now, my little project does a basic transpilation, by tokenizing the code and just looking for a translation. I want to improve a bit more this, and was trying to use Putout. It works fine for EsJS -> JS, but I also want to have a bi-directional transpilation.

I tried Putout and get it working in a way, and I wonder if I can transform the code in the other way to replace my "basic transpilation" with Putout (and then look up for more improvements).

So, the options you mentioned doesn't resolve my needs... But, also maybe I'm doing this wrong, and will have to do this in others ways. What do you think? Thanks in advance!

**Comment by coderaiser** [comment]
Yes, [🤫Goldstein](https://github.com/coderaiser/goldstein) can help you do to what you want with help of:
- [`print`](https://github.com/coderaiser/goldstein#printast);
- [`convert`](https://github.com/coderaiser/goldstein#convertsource);

But the most important thing is [`@putout/printer`](https://github.com/putoutjs/printer#), you can override it in any way you want using Babel AST, here is [example](https://github.com/coderaiser/goldstein/blob/master/packages/printer/visitors/if-statement.js).

**Comment by enzonotario** [comment]
Nice, thank you so much! 

I've checked Goldstein but I was looking at the Acorn Extension ([here](https://github.com/coderaiser/goldstein/blob/master/packages/keyword-if/index.js) for example). I'll check the Printer more in depth! Thanks!
