### ISSUE TITLE
ignore test files

### ISSUE THREAD

**Issue by phun-ky** [coderaiser/putout#199]
How do I ignore test files? From the documentation, and testing my self, only relative directories are ignored, with this setup, not globs:

```json
{
  "ignore": [
      "src/test/",
      "**/__tests_/**"
  ]
}

```

**Comment by coderaiser** [comment]
This should be enough:

```json
{
  "ignore": [
      "**/src/test",
      "**/__tests_"
  ]
}
```

**Comment by phun-ky** [comment]
@coderaiser tried that one just now, did not work :/

**Comment by coderaiser** [comment]
Create example repository, so I can check

**Comment by coderaiser** [comment]
Is it works for you?
