### ISSUE TITLE
breaking JSX

### ISSUE THREAD

**Issue by oprogramador** [coderaiser/putout#20]
I had this code:
```js
export const Hamburger = props => (
  <>
    <div className="bg-blue">
      <MenuContainer />
    </div>
  </>
);
```

putout changed it to:
```js
export const Hamburger = () => (
  <>
    <div className="bg-blue">
      <MenuContainer />
    </div>
                                     </>;
```

so beside a formatting issue, the closing bracket is removed causing a syntax error.
Only `remove-unused-variables` rule was switched on.

**Comment by coderaiser** [comment]
I can't reproduce this, I have such result:

```js
export const Hamburger = () => <>
    <div className="bg-blue">
        <MenuContainer />
    </div>
</>;
```

Please upgrade to latest version. Is it works for you?

**Comment by oprogramador** [comment]
I cannot reproduce now either.

I can reopen when I encounter this problem again.
