### ISSUE TITLE
path is missing for ruler toggler

### ISSUE THREAD

**Issue by milahu** [coderaiser/putout#200]
### repro

run putout in an empty dir

no `package.json`
no `.putout.json`

```
cd $(mktemp -d)
echo 'console.log(123)' >test.js
putout --enable-all
```

### actual

> ```🐊 `path` is missing for ruler toggler (`--enable-all`, `--disable-all`)```

### expected

use the current workdir as path

### workaround

```
putout --enable-all .
```

**Comment by coderaiser** [comment]
That’s interesting idea, but you can see in [Usage](https://github.com/coderaiser/putout#-usage) section:

```
putout [options] [path]
```

`—-enable-all` is options flag, and `path` should be provided. That’s interesting idea to set `.` as default flag, but what to do with `—-staged` flag, for example, it doesn’t work in current directory it works with staged files only.

**Comment by milahu** [comment]
nevermind, its better this way
