### ISSUE TITLE
babel config is not loaded.

### ISSUE THREAD

**Issue by krzysztofpniak** [coderaiser/putout#201]
How can I load `babel.config.js`?
I have a code:

```js
const source = "a |> b";

putout(source, {
      plugins: ['remove-unused-variables'],
    });
```
I got 
`This experimental syntax requires enabling the parser plugin: "pipelineOperator". (1:2)`

**Comment by coderaiser** [comment]
There is no way to load babel config, anyways everything works good for me 
https://putout.cloudcmd.io/#/gist/aa57aef60816b5d7875536b9271a701b/73337bbf9ac4cf9df51460ceaa9415ce742a7f19

What version of 🐊**Putout** are you using?

**Comment by krzysztofpniak** [comment]
I'm using the latest.

Please paste:
following code in plugin window:
```
export const report = () => `Use 'if condition' instead of 'ternary expression'`;

export const replace = () => ({
    '__a |> __b |> __c': 'if (__a) __b; else __c;'
});

```

**Comment by coderaiser** [comment]
Yes, this construction is’n supported now in Replacer, you can use Traverser instead. What result do you want to achieve: please provide input and output, and I try to help you.

**Comment by coderaiser** [comment]
It is easy to enable parsing of [pipelineOperator](https://babeljs.io/docs/babel-plugin-proposal-pipeline-operator), but what kind of topic to set?

It is also [stage-2](https://github.com/tc39/proposal-pipeline-operator) so lots things can be changed and it is not supported by any runtime as I know. Are you using `pipelineOperator` in production and want to get rid of it?

**Comment by krzysztofpniak** [comment]
Thanks, I would like to transform:
`expr1 |> expr2 |> expr_n`
to:
`wrap(expr1).pipe(expr2).pipe(expr_n).value`

**Comment by krzysztofpniak** [comment]
I'm using
```
[
      '@babel/plugin-proposal-pipeline-operator',
      {proposal: 'minimal'},
],
```

**Comment by coderaiser** [comment]
Do you need any additional help for this?

**Comment by krzysztofpniak** [comment]
Yes, I tries Traverser and it gives me the same error.
```
export const report = () => `replace pipelines`;

export const traverse = ({push}) => ({
  BinaryExpression: path => console.log('path', path),
});
```

**Comment by coderaiser** [comment]
Did you update [babel plugins](https://github.com/coderaiser/putout/blob/v35.15.0/packages/engine-parser/lib/parsers/babel/plugins.js)?

**Comment by krzysztofpniak** [comment]
> Yes, this construction is’n supported now in Replacer (good idea for PR to `@putout/engine-parser`), you can use [Traverser](https://github.com/coderaiser/putout/tree/master/packages/engine-runner#traverser) instead. What result do you want to achieve: please provide input and output, and I try to help you.

You mentioned that it will work in Traverser. However, it seems that manual changes are required in the plugins within the node_modules directory each time, and on every machine I need to use it. Do you have any better ideas on how I can achieve this?

**Comment by coderaiser** [comment]
https://www.npmjs.com/package/patch-package can help with this, but why don't you want to run transform once and commit to git repository. Do you need to run it every time you write code?

**Comment by krzysztofpniak** [comment]
patch-packages + change in @putout/engine-parser solves all my issues. Thanks for your help.
