### ISSUE TITLE
@putout/printer: Removed useful comma in TS

### ISSUE THREAD

**Issue by coderaiser** [coderaiser/putout#207]
Started in #206
1 - how it is with ts error
2 - how it should be (was before)

Case 1

```ts
const MultiChips = <T>({items, idProperty, labelProperty, onRemove, xs, lg, md, sm, getLabel, disabled}: Props<T>): JSX.Element => {}
```

```ts
const MultiChips = <T,>({items, idProperty, labelProperty, onRemove, xs, lg, md, sm, getLabel, disabled}: Props<T,>): JSX.Element => {}
```

@AlexanderAbramovPav, the comma in `<T,>` and `Props<T,>` is needed and you do not want it be removed?

**Comment by AlexanderAbramovPav** [comment]
Yes, I wanna keep comma, cause I'm getting TS error otherwise

**Comment by coderaiser** [comment]
What kind of error? Could you please provide an example?

**Comment by coderaiser** [comment]
<img width="580" alt="image" src="https://github.com/coderaiser/putout/assets/1573141/6a32dcba-dca9-420f-adc6-d049660c6742">

**Comment by AlexanderAbramovPav** [comment]
For case 1

![image](https://github.com/coderaiser/putout/assets/95632162/6dd4c5b7-d94e-47fd-a416-1ca8b7d36440)

**Comment by coderaiser** [comment]
Re-install 🐊**Putout**, is it works for you?

**Comment by AlexanderAbramovPav** [comment]
Yes!
