### ISSUE TITLE
How to use indetifier name as a string?

### ISSUE THREAD

**Issue by artalar** [coderaiser/putout#209]
Hi there! Thanks you for this super powerful tool. Can you help me, how can I use an indetifier string representations as a string? If I wrap it to a quotes, it removes for some reason...

![image](https://github.com/coderaiser/putout/assets/27290320/ee222b07-d0cd-4b41-a2bd-9c1a76e847e3)

**Comment by coderaiser** [comment]
I replaced with `__a` which is identifier, the placeholders cannot change it’s type.

Here is how it can look like:
- 🐊[Mobile Putout Editor](https://putout.vercel.app/#/gist/b71eeccbddb9b63f073fdb14e6bdb45a/b98f27428ab714ab0529a4427b9071992882089e);
- 🐊[**Putout Editor**](https://putout.cloudcmd.io/#/gist/b71eeccbddb9b63f073fdb14e6bdb45a/b98f27428ab714ab0529a4427b9071992882089e);

And don’t forget that `__a` can also be [`ObjectPattern`](https://github.com/coderaiser/putout/blob/master/docs/the-book-of-ast.md#objectexpression-and-objectpattern) or [`ArrayPattern`](https://github.com/coderaiser/putout/blob/master/docs/the-book-of-ast.md#arrayexpression-and-arraypattern).

**Comment by artalar** [comment]
Awesome, thank you!

**Comment by coderaiser** [comment]
You can also use [`@putout/plugin-putout`](https://github.com/coderaiser/putout/tree/master/packages/plugin-putout#check-replace-code), it reports such cases:

<img width="911" alt="image" src="https://github.com/coderaiser/putout/assets/1573141/e05e2c69-9f37-4ef9-8061-e99fa0da8ac9">

And see this error inside 🐊[**Mobile Putout Editor**](https://putout.vercel.app/)

<img width="1179" alt="image" src="https://github.com/coderaiser/putout/assets/1573141/3daae26e-9f06-4e22-8b77-fdd2ce46ce19">

**Comment by coderaiser** [comment]
I have and idea, that can make such plugin even simpler:

```js
export const report = () => `Add argument to 'reatomComponent'`;

export const replace = ({
    'const __identifier__a = atom(__b)': 'const __identifier__a = atom(__b, __extract(__identifier__a))',
}
```

In this case no matcher will be needed. @artalar What do you think about such syntax?

`__extract` is [`extract`](https://github.com/coderaiser/putout/tree/master/packages/operate#extractpath) from [`@putout/operate`](https://github.com/coderaiser/putout/tree/master/packages/operate#readme).
