### ISSUE TITLE
eslint-plugin-putout and ESLint Shareable Configs

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#21]
I am trying to integrate eslint-plugin-putout into my ESLint shareable config - [eslint-config-hardcore](https://github.com/EvgenyOrekhov/eslint-config-hardcore).

The integration of putout itself was straightforward.
But I don't understand how I can **override putout rules in my shareable ESLint config**.

I see that it is possible to create `.putout.json` in projects that will be using eslint-hardcore-config, but I would like to avoid having to create and maintain `.putout.json` in each project. I would like my putout config to be shared along with my eslint-hardcore-config.

For example, [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier#options) allows you to specify Prettier options like this (in `.eslintrc.json`):

```json
{
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": ["error", { "singleQuote": true }]
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  }
}
```

I would like to be able to do something like that with putout:

```json
{
  "plugins": ["putout"],
  "rules": {
    "putout/putout": [
      "error",
      {
        "rules": {
          "apply-optional-chaining": "on",
          "apply-nullish-coalescing": "on",
          "remove-unused-variables": "off"
        }
      }
    ]
  }
}
```

**Comment by coderaiser** [comment]
This is a very good question :), yes it is possible, just added information about this to `README` with e451055.
Unfortunately `putout` rule of `eslint-plugin-putout` can't just use `rules` as a list, and should have additional `rules` field, like this:

```json
  {
    "rules": {
        "putout/putout": ["error", {
            "rules": {
                "remove-unused-variables": "off"
            }
        }]
    }
}
```

This is made for a reason: you can [configure](https://github.com/coderaiser/putout#configuration) more things with `putout` then with `prettier`, there is also `ignore` and `match` sections. And configuration is merged using [parse-options](https://github.com/coderaiser/putout/blob/v10.0.3/packages/eslint-plugin-putout/lib/putout/index.js#L36) with [other options](https://github.com/coderaiser/putout/blob/master/packages/putout/lib/parse-options/index.js#L37-L43). So yes, you can avoid creating `.putout.json` on every project if you don't want to and use only `shareable eslint config` :).

Is it works for you?

**Comment by EvgenyOrekhov** [comment]
@coderaiser Aw man, I should've just tried that right from the start :) Yes, it works perfectly for me, thank you!
