### ISSUE TITLE
Option to configure printer overrides from

### ISSUE THREAD

**Issue by MatthewScholefield** [coderaiser/putout#213]
I can't seem to find a way to configure tab size with putout. I see there are overrides within `putoutjs/printer` that can be specified like `"format": {"indent": "  "}`. However, it doesn't look like these overrides are being passed through from the putout config. I tried adding the following in my `package.json`:
```json
  "putout": {
    "format": {
      "indent": "  "
    }
  }
```
And of course this fails indicating the field isn't valid:
```
.putout.json: format: must NOT have additional properties
error: "putout" exited with code 12
```

It'd be nice to allow customizing this so we could change indent size.

**Comment by MatthewScholefield** [comment]
Hmm, actually I see [this comment](https://github.com/coderaiser/putout/issues/144#issuecomment-1541592467) indicates it should theoretically work like this:

```json
  "putout": {
    "printer": [
      "putout",
      {
        "format": {
          "indent": "  "
        }
      }
    ]
  }
```
While this doesn't error saying invalid config, it also doesn't seem to change the behavior of indentations.

**Comment by coderaiser** [comment]
Create `.putout.json` with:

```json
{
    "printer": ["putout", {
        "format": {
          "indent": "  "
        }
      }]
}
```

Is it works for you?

**Comment by MatthewScholefield** [comment]
Hmm, that doesn't work either. Here is a full example:
```console
$ cat > example.js
function testFn() {
return 123;
}
testFn();

$ cat > .putout.json
{"printer":["putout",{"format":{"indent":"  "}}]}

$ putout example.js --fix
$ cat example.js
function testFn() {
    return 123;
}

testFn();
$ putout --version
v35.37.1
```

**Comment by MatthewScholefield** [comment]
Haven't gotten time to finish investigating but right now after running off of a git clone I'm seeing:
```console
$ node ../putout/packages/putout/bin/putout.mjs example.js
🐊 .putout.json: printer: must NOT have more than 2 items
```
And the config it's evaluating has:
```
...
printer: [ 'putout', { format: [Object] }, { format: [Object] } ],
...
```
So it looks like maybe the default config's array is getting merged with the provided config's array?

**Comment by coderaiser** [comment]
Just fixed in 🐊**Putout** [v36](https://github.com/coderaiser/putout/releases/tag/v36.0.0). Is it works for you?

**Comment by MatthewScholefield** [comment]
Thanks so much for the quick response! Actually, it still didn't work with v36. Upon further investigation, the problem seems to be that I somehow have a file `~/.putout.json` which is causing this issue. After removing it, the problem is resolved. But of course a user-level config shouldn't mess with a repo config so the root cause should still probably be addressed.

I think a hacky solution might be to modify `arrayUnion` to check if `typeof a[0] == 'string' && typeof a[1] == 'object'` and do special merge logic under this condition. But in general, I wonder if changing the config paradigm from (pseudocode) `x || [x, options]` to `x || {value: x, options: options}` would be better. It's a little more verbose but then config merging could use standard recursive merge. However to keep backwards compatibility might be a bit clunky since it needs to then have all three (`x || [x, params] || {value: x, options: options}`).

By the way, thanks so much for the quick response / change!

**Comment by coderaiser** [comment]
What did you have in your `~/.putout.json` file?

**Comment by MatthewScholefield** [comment]
The exact same content:
```json
{"printer":["putout",{"format":{"indent":"  "}}]}
```

**Comment by coderaiser** [comment]
You can add additional merging options to [merge.js](https://github.com/coderaiser/putout/blob/master/packages/putout/lib/merge.js) with a test. Are you up for a PR?

**Comment by coderaiser** [comment]
Just fixed, please re-install 🐊**Putout**, is it works for you?
