### ISSUE TITLE
does more than asked for

### ISSUE THREAD

**Issue by adrian-gierakowski** [coderaiser/putout#215]
I've only got 1 rule enabled in `.putout.json`:

```json
{
    "rules": {
        "remove-unused-variables": "on"
    }
}
```

but after running `putout --fix path-to-my-file.ts` the entire file is reformatted, including things like converting try\catch to calls to `try-to-catch`, chading indentation, adding semicolons etc etc.

**Comment by coderaiser** [comment]
All rules enabled by default, but you can [disable any of them](https://github.com/coderaiser/putout#-what-is-ruler) printer also [highly configurable](https://github.com/coderaiser/putout?tab=readme-ov-file#printer) so you can configure 🐊**Putout** in any way you like.

**Comment by adrian-gierakowski** [comment]
@coderaiser so the rules are enabled even though they are not listed in my config? I did run `putout --disable-all` but it only flipped the one rule I had in my config to off

**Comment by coderaiser** [comment]
Yes, all rules enabled by default, that is not like ESLint, when you enable what you want, you disable what you want, if you need to set baseline use `putout . —-disable-all` this will disable all found rules violations, and then you can enable what you really want.
