### ISSUE TITLE
Closing arrow bracket (&gt;) inside React components should not be transformed into `>` automatically

### ISSUE THREAD

**Issue by Jabher** [coderaiser/putout#216]
`&gt;` inside React components is transformed into `>` automatically and uncontrolled, however, this behaviour causes troubles with other tools, such as prettier. 

E.g. (Putout **35.37.1** is used in this example)
```javascript
const putout = require("putout");

const { code } = putout(`
export default () => (<div>press here -&gt;</div>);
export const Component = () => (<div>&lt;- press here -&gt;</div>);
`);
console.log(code);
```

produces
```javascript
export default () => (
    <div>press here -></div>
);

export const Component = () => (
    <div>&lt;- press here -&gt;</div>
);
```

I understand that this is semi-correct behaviour and is generally handled by various transforms, but e.g. prettier+typescript that is embedded in my pipeline crashes on this transformation with this error:
```
SyntaxError: Unexpected token. Did you mean `{'>'}` or `&gt;`?
```

I can see that this transform gets disabled in case when pair of braces is used, so I guess this is some explicit internal behavior.

I recommend to move it to separate transformation (maybe enabled-by-default) so it can be optionally disabled to preserve compatibility with other linting tools in pipeline.

I'm currently replacing all `&gt;`s in my code with `{">"}`, but I hope it can be fixed in a future.

**Comment by coderaiser** [comment]
Thanks, just fixed in [`@putout/printer v9.9.0`](https://github.com/putoutjs/printer/releases/tag/v9.9.0)🎉. Is it works for you?
