### ISSUE TITLE
`eslint-plugin-putout` with ESLint flat config

### ISSUE THREAD

**Issue by abdul-alhasany** [coderaiser/putout#219]
Is the `eslint-plugin-putout` available for the new [ESLint flat config](https://eslint.org/blog/2022/08/new-config-system-part-2/)?

I tried using it this way:
```js
	...compat.config({
		extends: 'plugin:putout/recommended',
		rules: {
			'putout/add-newlines-between-specifiers': 'warn',
			'putout/add-newline-before-return': 'warn',
			'poutout/multiple-properties-destructuring': 'warn',
		},
	}),
```
but did not have much success.

**Comment by coderaiser** [comment]
Sure, here is [docs](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#flat)

**Comment by abdul-alhasany** [comment]
Thankks for the reply. 
This includes everything (including eslint and n config). I have my own config and I wanted to add few rules from `putout`. Is that possible?

**Comment by coderaiser** [comment]
You can turn off everything you don't need

**Comment by coderaiser** [comment]
Is it works for you?

**Comment by abdul-alhasany** [comment]
Unfortunately not as I want. The `recommneded` part adds all these:
```js
const nPlugin = require('eslint-plugin-n');
const {FlatCompat} = require('@eslint/eslintrc');
const putoutPlugin = require('..');
```
It is conflicting with my eslint config.

I only want `putout` part but it is not exported.

**Comment by coderaiser** [comment]
How it is conflicting in your config? Do you have any errors?

**Comment by coderaiser** [comment]
If you want only `putout` plugin was exported you can submit PR:

https://github.com/coderaiser/putout/blob/7eda682759840fbd2270807fdda0cd4152102141/packages/eslint-plugin-putout/lib/config/index.js#L5

**Comment by coderaiser** [comment]
Actually things much more simpler, if you don't need config, and just need a plugin use:

```js
import putout from 'eslint-plugin-putout';

export default [{
    plugins: {
        putout,
    },
    rules: {
        "putout/putout": "error"
    }
}];
```

That's it, plugins API didn't changed, only format of configs. Is it works for you?

**Comment by abdul-alhasany** [comment]
Great. It is working now. I find a couple of bugs in rules. I will submit separate issues for them
