### ISSUE TITLE
False CJS detection

### ISSUE THREAD

**Issue by jonataswalker** [coderaiser/putout#25]
Hi there, if I use this:

`export * from './foo.js';`

I get this warning:

`"use strict" directive should be on top of commonjs file (strict-mode/add) eslint(putout/putout)`

**Comment by coderaiser** [comment]
Thanks a lot :), fixed with a6debe8, landed in `@putout/plugin-strict-mode v2.0.0` and [putout v10.0.6](https://github.com/coderaiser/putout/releases/tag/v10.0.6) 🎉 .
Please reinstall `putout`. Is it works for you?

**Comment by jonataswalker** [comment]
Grateful. I'll ask `eslint-plugin-hardcore` for an upgrade.

**Comment by jonataswalker** [comment]
Fix confirmed.
