### ISSUE TITLE
Replace putout-plugin to @putout/plugin in README files of packages directory

### ISSUE THREAD

**Issue by coderaiser** [coderaiser/putout#26]
- [x] Replace `putout-plugin` to `@putout/plugin` in headers of `README.md` in `packages` directory similar to https://github.com/coderaiser/putout/commit/ea083359b1c082cb291b3d5ac218820eeaa5acea
- [ ] Update `true` to `"on"` similar to https://github.com/coderaiser/putout/commit/1dcbd9365497c966f141f9162f23846c60f90d33.

**Comment by fluentinstroll** [comment]
Hi there! Can I take on this issue?

**Comment by coderaiser** [comment]
@fluentinstroll yep, you can choose file from `packages/*/README.md` :).
