### ISSUE TITLE
Replace eslint ^7.0.0-rc.0 with eslint ^7.0.0

### ISSUE THREAD

**Issue by coderaiser** [coderaiser/putout#29]
Replace `rc` eslint version with stable similar to https://github.com/coderaiser/putout/commit/d826d7a45d7ffdfead3020f0e427554de0f43ccf in any count of `packages/*/package.json` and `codemods/*/package.json`

**Comment by tejaswankalluri82522** [comment]
@coderaiser I like to contribute
