### ISSUE TITLE
eslint-plugin-putout multiple-properties-destructuring minProperties

### ISSUE THREAD

**Issue by sajtosnorbert** [coderaiser/putout#3]
Is there any way of setting a value for minProperties?
Currently it's >2, but I would like to have a configurable value for the.

**Comment by coderaiser** [comment]
What a great idea for a pull request 🙂

https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins

**Comment by coderaiser** [comment]
Added support of `minProperties` in eslint-plugin-putout `v1.5.0` 🎉.
