### ISSUE TITLE
eslint-plugin-putout requires putout package

### ISSUE THREAD

**Issue by jameswomack** [coderaiser/putout#41]
I really appreciate that `'eslint-plugin-putout'` includes the following options:
```json
{
  "putout/single-property-destructuring": "error",
  "putout/multiple-properties-destructuring": "error"
}
```

That said, the plugin doesn't work out-of-the-box w/ [the provided instructions](https://github.com/coderaiser/putout/blob/master/packages/eslint-plugin-putout/README.md#installation). `'eslint-plugin-putout'` plugin requires the `'putout'` package. However, its read me doesn't instruct us to `npm i putout`, nor does the `'eslint-plugin-putout'` package install it or warn us that it needs to be intalled

The error that happens, silently in VS Code, is this
```
[Info  - 0:00:00 PM] Failed to load plugin 'eslint-plugin-putout' declared in '.eslintrc': 
Cannot find module 'putout' 
Require stack: - ./node_modules/eslint-plugin-putout/lib/keyword-spacing/index.js ...
```

My suggestion is to do the following
1. [ ] Add putout to the `npm i eslint eslint-plugin-putout` line of [the read me](https://github.com/coderaiser/putout/blob/master/packages/eslint-plugin-putout/README.md#installation)
1. [x] Add putout to [the peerDependencies](https://github.com/coderaiser/putout/blob/master/packages/eslint-plugin-putout/package.json#L47)
1. [ ] Add a try/catch around [a root `require('putout')`](https://github.com/coderaiser/putout/blob/b67449d0e9265769e0526d56d58774e4b3113d3e/packages/eslint-plugin-putout/lib/putout/index.js#L9) w/ a clear+friendly error message

If that sounds right to y'all, I'd be happy to open a pull request to that effect

**Comment by coderaiser** [comment]
That sounds absolutely right for me, I'm totally agree with you, you'r welcome :).

**Comment by jameswomack** [comment]
Awesome

@coderaiser I've created a `issue-41_putout-dep` branch in my fork but I notice the tests don't pass in master

**Comment by coderaiser** [comment]
@jameswomack I can't see failing tests, you can create PR and we will see what `travis` will tell us :).
