### ISSUE TITLE
how do you use the package stand lone by feeding a list of js files to remove IIFE

### ISSUE THREAD

**Issue by richie50** [coderaiser/putout#42]
@coderaiser i have a bunch of js code wrapper in IIFE and i want them removed. How do you achieve this

**Comment by coderaiser** [comment]
Here is a short example for one file, could you please provide more deteails.

```js
const {readFileSync, writeFileSync} = require('fs');
const putout = require('putout');

const input = readFileSync('./iife.js', 'utf8');
const output = putout(file, {
    plugins: [
        'remove-iife'
    ]
});

writeFileSync('./iife.js', output);
```

**Comment by richie50** [comment]
@coderaiser for example src/ folder  with .js files and  sub directories with .js files recursively. I guess with the above script i can recursively go thru each .js file in all directories and sub directories and use the remove-iife and write the output to the said file. 
Code below:

`//requiring path and fs modules
const path = require('path');
const fs = require('fs');
//joining path of directory 
const directoryPath = path.join(__dirname, 'src/app');

let walk = (directoryPath, fileList = []) => {
    const files = fs.readdirSync(directoryPath);
    files.forEach(function(file) {
        let isDirectory = fs.statSync(path.join(directoryPath, file)).isDirectory();
        if (isDirectory) {
            filelist = walk(path.join(directoryPath, file), fileList); // recursively go thru the sub directory call 
        } else {
            //console.log(file, " is a file ", !isDirectory);
            var jsFilterRegex = /\.js$/;
            if (jsFilterRegex.test(file)) {
                console.log("Removing IIFE with putout plugin  ", file);
                const input = fs.readFileSync(path.join(directoryPath, file), 'utf8');
                /**
                 * This part of the code is not tested with the putout plugin but you get the idea
                 */
                const output = putout(file, {
                    plugins: [
                        'remove-iife'
                    ]
                });
                fs.writeFileSync(directoryPath, file, output);
                /** Not tested  */
            }
            fileList.concat(path.join(directoryPath, file)); // store the files
        }
    });
    return fileList;
};
let all_files = []
all_files = walk(directoryPath, all_files);`

**Comment by coderaiser** [comment]
@richie50 you can use something like [this](https://github.com/coderaiser/putout/blob/v10.5.1/packages/putout/lib/cli/get-files.js) to simplify things a bit :).

**Comment by coderaiser** [comment]
Could you please tell me why do you need it? We can move out some stuff from `putout cli` into separate module to simplify using of such functionality in future :).

**Comment by richie50** [comment]
@coderaiser I just needed it to remove IIFE from an old angularJs projects. I was porting the application from ES2015 to Yypescript. And by the way i was able to apply your above code to remove all the IIFE. Thanks mate
