### ISSUE TITLE
Putout never completes

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#46]
Putout 13.2.0 worked fine. After I upgraded to 13.7.0, Putout can no longer complete, it just eats ~10% of my CPU and never finishes.

I'm using eslint-plugin-putout. I also tried running `node_modules/.bin/putout`, same result, it never finishes.

I does NOT reproduce on my CI, but it reproduces on my local machine (Windows 10, Node.js v14.15.4).

What can I do to gather more info?

**Comment by EvgenyOrekhov** [comment]
Tried different versions, 13.4.0 works, 13.5.0 does not work.

**Comment by coderaiser** [comment]
Could you please give me en example of files or repo where this is reproduced, I'll take a look.

**Comment by EvgenyOrekhov** [comment]
I think I found the cause. It's this line:

https://github.com/coderaiser/putout/blob/48be42c0c0864b161123529e813d64bed3b60a8c/packages/putout/lib/parse-options/recursive-read.js#L15

On a Windows machine `dir` ends up being `C:\` and the loop never terminates.

**Comment by coderaiser** [comment]
Thanks a lot :), fixed with 5fd158b, landed in [v13.7.1](https://github.com/coderaiser/putout/releases/tag/v13.7.1) 🎉.

Is it works for you?

**Comment by EvgenyOrekhov** [comment]
It works, thank you!
