### ISSUE TITLE
Putout doesn't work in VS Code via ESLint

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#48]
VS Code comes bundled with Node v12, but Putout now requires Node v14.

![image](https://user-images.githubusercontent.com/8045060/106150731-aebefd00-618c-11eb-9e6a-0b1f27c6ebdb.png)

ESLint with Putout just doesn't work, this is what I get in VS Code log:

```text
[Info  - 2:41:11 PM] ESLint server is starting
[Info  - 2:41:12 PM] ESLint server running in node v12.14.1
[Info  - 2:41:12 PM] ESLint server is running.
[Info  - 2:41:16 PM] ESLint library loaded from: C:\eslint-config-hardcore\node_modules\eslint\lib\api.js
[Info  - 2:41:21 PM] Failed to load plugin 'putout' declared in '.eslintrc.json » ./index.json » ./base.json': Cannot find module 'putout/parse-options' Require stack: - C:\eslint-config-hardcore\node_modules\eslint-plugin-putout\lib\putout\index.js - C:\eslint-config-hardcore\node_modules\eslint-plugin-putout\lib\index.js - C:\eslint-config-hardcore\node_modules\@eslint\eslintrc\lib\config-array-factory.js - C:\eslint-config-hardcore\node_modules\@eslint\eslintrc\lib\index.js - C:\eslint-config-hardcore\node_modules\eslint\lib\cli-engine\cli-engine.js - C:\eslint-config-hardcore\node_modules\eslint\lib\cli-engine\index.js - C:\eslint-config-hardcore\node_modules\eslint\lib\api.js - c:\Users\user\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\server\out\eslintServer.js
```

**Comment by coderaiser** [comment]
`2021-03-02` [electron with node v14 support became stable](https://www.electronjs.org/docs/tutorial/electron-timelines).
For now fixed with,
landed to:
🎈  [putout v14.0.2](https://github.com/coderaiser/putout/releases/tag/v14.0.2)
🎈 [eslint-plugin-putout v7.0.1](https://www.npmjs.com/package/eslint-plugin-putout)
 
Is it works for you?

**Comment by EvgenyOrekhov** [comment]
Thank you, it works now!

BTW, note that VS Code might not migrate to Electron v12 right after its release, they might do it several months later.

**Comment by coderaiser** [comment]
Looks like `node v14` already supported by [vs code](https://code.visualstudio.com/updates/v1_60#_engineering)🎈.
