### ISSUE TITLE
plugin-split-nested-destructuring: add support for function parameters

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#49]
[`@putout/plugin-split-nested-destructuring`](https://github.com/coderaiser/putout/tree/master/packages/plugin-split-nested-destructuring) works for assignments, but it doesn't do anything with function parameters. I would like it to split nested destructuring of function parameters into separate `const` statements:

```js
// before:
function f({ a: { b } }) {
  console.log(b);
}

// after:
function f({ a }) {
  const { b } = a;
  console.log(b);
}
```

**Comment by coderaiser** [comment]
Thanks a lot for a nice idea :), landed in`@putout/plugin-split-nested-destructuring v1.1.0` 🎉 .
Please reinstall `putout`.

Is it works for you?

**Comment by EvgenyOrekhov** [comment]
@coderaiser Yes, it works, thank you!

Why don't I see mentions of `@putout/plugin-split-nested-destructuring` update in the [changelog](https://github.com/coderaiser/putout/blob/master/packages/putout/ChangeLog) though?

**Comment by coderaiser** [comment]
> Why don't I see mentions of @putout/plugin-split-nested-destructuring update in the changelog though?

You will see it in `ChangeLog` on next release of `putout` :).
