### ISSUE TITLE
eslint-plugin-putout can't detect JSX

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#53]
When I try to lint a simple `*.tsx` file, like

```tsx
function MyComponent() {
  return (
    <div>Hello</div>
  );
}
```

ESLint gives me the following error:

```text
SyntaxError: Unterminated regular expression
```

With other `*.tsx` files it gives me the following error:

```text
SyntaxError: Unexpected token, expected "</>/<=/>="
```

When I disable the `putout/putout` rule, ESLint and all other plugins start to work fine.

So, as I understand it, Putout can't detect that `*.tsx` files use JSX.

**Comment by coderaiser** [comment]
Currently to determine that `jsx` is used, and plugin `jsx` should be connected to babel parser [getJSX](https://github.com/coderaiser/putout/blob/v16.4.0/packages/engine-parser/lib/parsers/babel/index.js#L15) is used, it checks if source file has `react` variable.

Don't you `require` react? Could you please show me full file content?

**Comment by EvgenyOrekhov** [comment]
We use [Stencil](https://stenciljs.com/). Stencil components don't have `React` import. You can see an example of Stencil component here: https://stenciljs.com/docs/my-first-component.

**Comment by EvgenyOrekhov** [comment]
It works, thank you!
