### ISSUE TITLE
remove async/await

### ISSUE THREAD

**Issue by retorquere** [coderaiser/putout#54]
I have a class definition that looks like 

```
class X {

    constructor() {
        this._analyzer = null;
    }

    async init(arg) {
       await something()
    }
}
```

and I need to strip `async` and `await` from/in method `init`. This is a source that is not under my control, but which I know will work without async in my own context, where I need it to be sync. How would I do this with putout?

**Comment by coderaiser** [comment]
Thank you for such a good question :). You can use such code mode:

```js
module.exports.report = () => 'async should be striped from init method';

module.exports.fix = (path) => {
    path.node.async = false;
    
    path.traverse({
        AwaitExpression(path) {
            path.replaceWith(path.node.argument);
        }
    });
}

module.exports.traverse = ({push}) => ({
    ClassMethod: (path) => {
        const keyPath = path.get('key');
        
        if (!keyPath.isIdentifier({name: 'init'}))
            return false;
        
        if (!path.node.async)
            return false;
        
        push(path);
    }
});
```

It works this way (you can try it in [putout editor](https://putout.cloudcmd.io):
![image](https://user-images.githubusercontent.com/1573141/115141041-f4c88600-a042-11eb-802b-3d82086ec0c7.png)

To run this `codemod` it in your codebase use, create file `remove-async-await.js` in directory `codemods` and run:

```sh
putout --rulesdir codemods .
``` 

It will find all occurrences which can be fixed with:

```sh
putout --rulesdir codemods . --fix
```

If you want to disable all other `putout` rules first, use:

```sh
putout --disable-all .
```

It will create file `.putout.json` with all found built-in rules violations disabled.

Is it worked for you?

**Comment by retorquere** [comment]
Sweet! How can I use this from JS code? Right now I have created a `codemods` with the file `remove-async-await.js`, but when I run this:

```
const fs = require('fs')
const putout = require('putout');

const source = fs.readFileSync('node_modules/kuroshiro/src/core.js', 'utf-8')
console.log(putout(source, { plugins: [ 'remove-async-await' ] }).code)
```

I get

```
/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-loader@4.1.1/node_modules/@putout/engine-loader/lib/load.js:24
        throw Error(`${bigFirst(type)} "${namespace}-${type}-${name}" could not be found!`);
        ^

Error: Plugin "putout-plugin-remove-async-await" could not be found!
    at /Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-loader@4.1.1/node_modules/@putout/engine-loader/lib/load.js:24:15
    at loadPlugins (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-loader@4.1.1/node_modules/@putout/engine-loader/lib/index.js:153:38)
    at module.exports.loadPlugins (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-loader@4.1.1/node_modules/@putout/engine-loader/lib/index.js:79:21)
    at transform (/Users/emile/github/better-bibtex/node_modules/.pnpm/putout@16.7.0/node_modules/putout/lib/putout.js:91:21)
    at module.exports (/Users/emile/github/better-bibtex/node_modules/.pnpm/putout@16.7.0/node_modules/putout/lib/putout.js:51:20)
    at Object.<anonymous> (/Users/emile/github/better-bibtex/tt.js:5:13)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

**Comment by retorquere** [comment]
There's also two other transforms I'm trying to get going; 1st is to transform

```
     parse(str = "") {
       return new Promise((resolve, reject) => {
           if (str.trim() === "") return resolve([]);
             const result = this._analyzer.tokenize(str);
             for (let i = 0; i < result.length; i++) {
                 result[i].verbose = {};
                 delete result[i].word_type;
                 delete result[i].word_position;
             }
           resolve(result);
       });
     }
```

into

```
     parse(str = "") {
           if (str.trim() === "") return [];
             const result = this._analyzer.tokenize(str);
             for (let i = 0; i < result.length; i++) {
                 result[i].verbose = {};
                 delete result[i].word_type;
                 delete result[i].word_position;
             }
           return result;
     }
```

with the 2nd I have an object

```
var CSL = {
      PROCESSOR_VERSION: "1.4.59",
      debug: function(str) { // default debug function
        if ("undefined" === typeof console) {
            dump("CSL: " + str + "\n");
        } else {
            console.log("citeproc-js warning: " + str);
        }
    },

    toLocaleUpperCase(str) {
        var arr = this.tmp.lang_array;
        try {
            str = str.toLocaleUpperCase(arr);
        } catch (e) {
            str = str.toUpperCase();
        }
        return str;
    },

    LOCATOR_LABELS_REGEXP: new RegExp('.'),

    // many more attributes
}
```

where I want to remove a list of named attributes (eg `toLocaleUpperCase`) from the object, regardless of their type.

**Comment by coderaiser** [comment]
> Sweet! How can I use this from JS code? Right now I have created a codemods with the file remove-async-await.js

It will look this way:

```js
const fs = require('fs')
const putout = require('putout');
const removeAsyncAwait = require('./codemods/remove-async-await');

const source = fs.readFileSync('node_modules/kuroshiro/src/core.js', 'utf-8');
const {code} = putout(source, {
    plugins: [
        ['remove-async-await', removeAsyncAwait],
    ]
});

console.log(code);
```

Is it works for you?

**Comment by coderaiser** [comment]
Here is transform for `new Promise`, it uses [getTemplateValues](https://github.com/coderaiser/putout/tree/master/packages/compare#gettemplatevaluesnode-template) to get `ArrowFunctionExpression` from `ReturnStatement`:

```js
const {operator, types} = require('putout');
const {replaceWith, getTemplateValues} = operator;
const {ReturnStatement} = types;

module.exports.report = () => 'Promise should be removed';

module.exports.fix = (path) => {
    const returnPath = path.get('body.body.0');
    const returnNode = returnPath.node;
    const {__a} = getTemplateValues(returnNode, 'return new Promise(__a)');
    
    const {body} = __a.body;
    const n = body.length - 1;
    body[n] = ReturnStatement(body[n].expression.arguments[0]);
    
    replaceWith(returnPath, __a.body);
}

module.exports.traverse = ({push}) => ({
    ClassMethod(path) {
        const keyPath = path.get('key');
        const isParse = keyPath.isIdentifier({
            name: 'parse',
        });
        
        if (isParse)
            push(path);
    }
});
```
It works this way:
![image](https://user-images.githubusercontent.com/1573141/115199919-5c8ed780-a0fc-11eb-9d4e-c5f50ceef2fa.png)

`Nested blocks` can be removed with [@putout/remove-nested-blocks](https://github.com/coderaiser/putout/tree/v16.7.0/packages/plugin-remove-nested-blocks).

About list of keys you want to remove it will look this way:

![image](https://user-images.githubusercontent.com/1573141/115201195-b643d180-a0fd-11eb-8da3-3e6dd73d246c.png)

And here is the code:

```js
const {operator, types} = require('putout');
const {replaceWith, getTemplateValues} = operator;
const {ReturnStatement} = types;

module.exports.report = () => 'toLocalUpperCase should be removed';

module.exports.fix = (path) => {
    path.remove();
}

module.exports.traverse = ({push}) => ({
    ObjectMethod(path) {
        const keyPath = path.get('key');
        const list = [
            'toLocaleUpperCase'
        ];
        
        for (const name of list) {
            if (keyPath.isIdentifier({name}))
                push(path);
        }
    }
});
```

So you will have 3 files in your `codemods` directory :).

Is it works for you?

**Comment by retorquere** [comment]
The first one works splendidly!

> Here is transform for new Promise, it uses getTemplateValues to get ArrowFunctionExpression from ReturnStatement:

with this one I get 

```
/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-runner@10.0.1/node_modules/@putout/engine-runner/lib/run-fix.js:15
    throw e;
    ^

TypeError: Cannot read property 'body' of undefined
    at module.exports.fix (/Users/emile/github/better-bibtex/codemods/remove-promise-wrapper.js:12:24)
    at module.exports (/Users/emile/github/better-bibtex/node_modules/.pnpm/try-catch@3.0.0/node_modules/try-catch/lib/try-catch.js:5:23)
    at tryToFix (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-runner@10.0.1/node_modules/@putout/engine-runner/lib/run-fix.js:8:17)
    at module.exports (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-runner@10.0.1/node_modules/@putout/engine-runner/lib/run-fix.js:24:5)
    at push (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-runner@10.0.1/node_modules/@putout/engine-runner/lib/merge-visitors.js:92:9)
    at ClassMethod (/Users/emile/github/better-bibtex/codemods/remove-promise-wrapper.js:27:13)
    at NodePath._call (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.13.15/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.13.15/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.13.15/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.13.15/node_modules/@babel/traverse/lib/context.js:116:16) {
  loc: { line: 76, column: 4 }
}
```

> About list of keys you want to remove it will look this way:

With this one I get

```
AssertionError [ERR_ASSERTION]: No tab width specified but encountered tabs in string
/>[	 ]+</g
    at Object.fromString (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/lines.js:580:22)
    at genericPrintNoParens (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/printer.js:693:28)
    at genericPrint (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/printer.js:123:30)
    at print (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/printer.js:77:15)
    at /Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/patcher.js:151:28
    at Array.forEach (<anonymous>)
    at /Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/patcher.js:139:18
    at print (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/printer.js:76:17)
    at /Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/printer.js:49:41
    at Object.printComments (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+recast@1.3.0/node_modules/@putout/recast/lib/comments.js:281:22) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

`getTemplateValues` is going to be a big help.

**Comment by coderaiser** [comment]
Could you please provide me examples of code that cause exception? Looks like this is not the code you provided before, because that one works good in [putout editor](https://putout.cloudcmd.io). I think they differ in a minor case which anyways should be checked separately like a `fixtures`.

You can read more about `modifying of AST` in [babel handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md).

**Comment by retorquere** [comment]
I tried to minimize the samples, but the code being modified is:

* `node_modules/kuroshiro-analyzer-kuromoji/src/index.js` from `kuroshiro-analyzer-kuromoji` (applying "Promise should be removed")
* `node_modules/citeproc/citeproc_commonjs.js` from the `citeproc` package (applying "toLocalUpperCase should be removed")

I'll dive into the babel handbook, thanks!

**Comment by coderaiser** [comment]
Looks like [reject](https://github.com/hexenq/kuroshiro-analyzer-kuromoji/blob/master/src/index.js) should be converted to `throw`.

**Comment by retorquere** [comment]
That is a good point.

**Comment by coderaiser** [comment]
File [citeproc](https://github.com/Juris-M/citeproc-js/blob/master/citeproc_commonjs.js) is generated, would be better to work with `src` directory and [build this file](https://github.com/Juris-M/citeproc-js#building-the-processor) after transformations.

By the way you can test `codemods` using [@putout/test](https://github.com/coderaiser/putout#testing), it uses `fixtures`, and make testing edge cases very simple and pleasant task :).

**Comment by coderaiser** [comment]
Here is simplified version for [kuroshiro-analyzer-kuromoji/src/index.js](https://github.com/hexenq/kuroshiro-analyzer-kuromoji/blob/master/src/index.js)

```js
const {operator, types} = require('putout');
const {replaceWith, getTemplateValues} = operator;
const {ReturnStatement, ThrowStatement} = types;

module.exports.report = () => 'Promise should be removed';

module.exports.replace = () => ({
    'return new Promise(__a)'({__a}, path) {
        replaceWith(path, __a.body);
        return path;
    },
    
    'reject(__a)': ({__a}, path) => {
        replaceWith(path.parentPath, ThrowStatement(__a));
        return path;
    },
    'resolve(__a)': ({__a}, path) => {
        replaceWith(path.parentPath, ReturnStatement(__a));
        return path;
    }
});

```

![image](https://user-images.githubusercontent.com/1573141/115276383-9d620d00-a14b-11eb-8dde-76930cec8b1f.png)

**Comment by coderaiser** [comment]
Just landed [promises/convert-new-promise-to-async](https://github.com/coderaiser/putout/tree/master/packages/plugin-promises#convert-new-promise-to-async) 🎉 , thank you for inspiration :).

**Comment by retorquere** [comment]
Superb -- the promise unwrapper does the job and `emove-nested-blocks` does the rest.

> File citeproc is generated, would be better to work with src directory and build this file after transformations.

I'm installing the node package, and that only has the generated file. I'll see if I can put together a replacer that strips them.

**Comment by retorquere** [comment]
Man, I'm dump. There's no need for me to strip citeproc -- the dead code elimination of the bundler I use does a better job than I did, automatically.

**Comment by retorquere** [comment]
> Thank you for such a good question :). You can use such code mode:
> 
> ```js
> module.exports.report = () => 'async should be striped from init method';
> 
> module.exports.fix = (path) => {
>     path.node.async = false;
>     
>     path.traverse({
>         AwaitExpression(path) {
>             path.replaceWith(path.node.argument);
>         }
>     });
> }
> 
> module.exports.traverse = ({push}) => ({
>     ClassMethod(path) {
>         const keyPath = path.get('key');
>         
>         if (!keyPath.isIdentifier({name: 'init'}))
>             return false;
>         
>         if (!path.node.async)
>             return false;
>         
>         push(path);
>     }
> });
> ```
> 
> It works this way (you can try it in [putout editor](https://putout.cloudcmd.io)): ![image](https://user-images.githubusercontent.com/1573141/115141041-f4c88600-a042-11eb-802b-3d82086ec0c7.png)
> 
> To run this `codemod` it in your codebase use, create file `remove-async-await.js` in directory `codemods` and run:
> 
> ```shell
> putout --rulesdir codemods .
> ```
> 
> It will find all occurrences which can be fixed with:
> 
> ```shell
> putout --rulesdir codemods . --fix
> ```
> 
> If you want to disable all other `putout` rules first, use:
> 
> ```shell
> putout --disable-all .
> ```
> 
> It will create file `.putout.json` with all found built-in rules violations disabled.
> 
> Is it worked for you?

This doesn't seem to work anymore in the latest putout
