### ISSUE TITLE
Destructuring Iterable that is not an Array uses .slice() 

### ISSUE THREAD

**Issue by chrispaterson** [coderaiser/putout#55]
Using the eslint plugin, I'm seeing a destructured `Set` be undestructured (restructured?) with a `.slice()` call, in typescript.  So this:

```typescript
const draftSet = new Set<string>([...rejected]);
```

becomes:
```typescript
const draftSet = new Set<string>(rejected.slice());
```

Where `rejected` is a `Set`.  

A `Set`, of course,  does not have a `slice` method.

**Comment by coderaiser** [comment]
Could you please tell me why do you create new `Set` from old one?

**Comment by coderaiser** [comment]
Just updated `@putout/plugin-convert-array-copy-to-slice` so it don't touch arguments to `new Set`.
Also add new case to `@putout/plugin-remove-useless-spread`, looks like you can just use:

```ts
const draftSet = new Set<string>(rejected);
```

And even:

```ts
const draftSet = new Set(rejected);
```

And it will be successfully consumed by `Set` constructor with all types checked :).

![image](https://user-images.githubusercontent.com/1573141/115534294-50437f80-a2a0-11eb-8da5-3978dbed6081.png)


Is it works for you?

**Comment by chrispaterson** [comment]
> Could you please tell me why do you create new `Set` from old one?

I'm using React which requires that state object updates are immutable; so an update has to be a new reference.

> Just updated @putout/plugin-convert-array-copy-to-slice v1.3.0 so it don't touch arguments to new Set.

Thanks for the quick turnaround!
