### ISSUE TITLE
Disable all rules

### ISSUE THREAD

**Issue by silverwind** [coderaiser/putout#60]
I'd like to use only the `convert-commonjs-to-esm` rule and not all the others that come in the default configuration. Is there a way to disable all rules without specifying them individually? e.g. something like `"all": "off"`?

Generally, I'd argue the default configuration should contain no rules, just like eslint does it.

**Comment by coderaiser** [comment]
The thing is the rules `putout` has is best practices, and it is recommended to use it. So yes, there is a difference with `eslint`, that it should have most rules enabled to keep your code base in best quality it can be :).

Anyways, there is an option `--disable-all`, which will disable all rules that was found by `putout` running on your codebase and save configuration into `.putout.json`. So you don't need to apply all rules `putout` suggest's and after setting `baseline` you can benefit from `putout` small suggestions while you writing new code.

It can look this way:

```
putout . --disable-all
```

**Comment by silverwind** [comment]
Thanks, that seems to help. I still disagree about default rules thought, rules will always be subjective and will never suit everyone. The only sane default for such tools is a empty default ruleset, allowing to configure advanced users exactly what they need. Beginners can just `extend` your base config.

**Comment by coderaiser** [comment]
I’m understand what you talking about and want to mention that the idea of least configuration is just what you said: advanced users that knows what they want can configure only what the need, for least experienced developers defaults is preferred, so they do not need to configure anything (creating same files again, and again) and keep codebase in a very good state.

There is also `putout` API, where you can choose only things that needed with:

```js
const {code} = putout(‘const a = “hello”’, {
    fix: true,
    plugins: [
        ‘convert-commonjs-to-esm’
    ]
});
```

This code will run only one chosen plugin.
Here is examples of using:
- in [mock-import](https://github.com/coderaiser/mock-import/blob/v1.0.7/lib/convert-imports/index.js)
- in [cloudcmd](https://github.com/coderaiser/cloudcmd/blob/v15.9.4/server/user-menu.js#L100-L107)

About eslint handling things, there is a couple differences:
- putout changes behaviour of changed code;
- putout has progress bar;
- all plugins of putout is modules;
- there is no warnings, only errors;
- plugins api much simpler;
- testing api has test descriptions, and have ability to `skip`, and put `only` (any count);
- all plugins are fixable;
- there is processors, that supports extending to support all kinds off files you ever need;

So yes, there is a lot differences, and this is the reason this project exists :).

**Comment by coderaiser** [comment]
@silverwind there is simplified way of converting `Commonjs` to `ESM` [exists](https://github.com/coderaiser/putout#-converting-commonjs-to-esm), and ability to disable all options for CLI :).
