### ISSUE TITLE
What is the reasoning behind remove-empty/import?

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#65]
Using "empty" imports for side effects is a fairly common practice:

```js
// jest.setup.js
import "@testing-library/jest-dom/extend-expect.js";
```

What is the reasoning behind removing them by default?

**Comment by coderaiser** [comment]
Because it’s not common practice, and there is a lot ways to `import` module like `fs`:

```js
import ‘fs’;
```

That has no sense. Also with help of [ignore option](https://github.com/coderaiser/putout/tree/v18.3.0/packages/plugin-remove-empty) any most used this way modules can be added.

**Comment by EvgenyOrekhov** [comment]
Not sure about built-ins, but using empty imports is used pretty often by 3rd-party libraries.

Thanks for clarifications, I decided to disable `remove-empty/import` (along with [`import/no-unassigned-import`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unassigned-import.md)) in eslint-config-hardcore: https://github.com/EvgenyOrekhov/eslint-config-hardcore/releases/tag/v19.10.0.

**Comment by coderaiser** [comment]
I see that [jest-dom](https://github.com/testing-library/jest-dom) suggest to use:

```js
import '@testing-library/jest-dom'
```

Let's look what is inside [src/extend-expect.js](https://github.com/testing-library/jest-dom/blob/0e34a35e6d47df654a939b4d71d13b2f340aa605/src/extend-expect.js
):

```js
import * as extensions from './matchers'
expect.extend(extensions)
```

You can use similar approach and this is is more obvious to understand what is going on here without any documentation. [supertape](https://github.com/coderaiser/supertape#testextendextensions) behave in a similar way:

```js
const {extend} = require('supertape');
const test = extend({
    transform: (operator) => (a, b, message = 'should transform') => {
        const {is, output} = operator.equal(a + 1, b - 1);
        return {
            is,
            output,
        };
    },
});

test('assertion', (t) => {
    t.transform(1, 3);
    t.end();
});
```

With no pollution of global scope. Many task runners adds global variables but I don't think this is a good practice for example js-based [Test Anything Protocol](https://testanything.org/)  runners can work  without separated utility you just execute your test with:

```js
node test.js
``` 

And it just works as any other script, with `jest`, `mocha` etc you can do such thing.
Anyways `jest` is very good task runner with a lot of features, `supertape` is the complete oppositeЖ the realm of minimalism :).

Also worth mention that: **Explicit is better than implicit** according to [Zen of Python](https://www.python.org/dev/peps/pep-0020/). Also such a way is violates **[Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)**: when you see empty `import` first thing you want to do is delete it (if it's not `css` in `React Component` of course).

**Comment by EvgenyOrekhov** [comment]
I agree that it would be better to avoid unassigned imports, but unfortunately many libraries recommend using unassigned imports in the official docs, and it just becomes annoying to see false-positive warnings from `import/no-unassigned-import` and `remove-empty/import`.
