### ISSUE TITLE
Issue with relative paths

### ISSUE THREAD

**Issue by Gianthra** [coderaiser/putout#7]
I had an issue with this on windows with relative paths

`RangeError: path should be a 'path.relative()'d string, but got "C:\<path\to\root>\dist\main.js"`

https://github.com/coderaiser/putout/blob/ecbca2a89d11e42dbeb6e3edcce28e39f73a289e/packages/putout/bin/putout.js#L129

I fixed this with:
```JavaScript
if (ignores(dir, name.replace(/^\./, cwd), options)) {
```

**Comment by coderaiser** [comment]
Could you please show me what kind of relative path have you used?

**Comment by Gianthra** [comment]
My relative path was `./dist/main.js`
I tried several variations on them however.
it resolves to `C:\<path\to\root>\`

**Comment by coderaiser** [comment]
Landed in [v5.0.1](https://github.com/coderaiser/putout/releases/tag/v5.0.1) 🎉. Is it works for you?
