### ISSUE TITLE
Suggestion to have `remove-empty/import` off by default

### ISSUE THREAD

**Issue by egilll** [coderaiser/putout#76]
Hi. [Importing a module for its side effects only](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only) is very common, such as with:

```js
import "core-js/stable";
import "regenerator-runtime/runtime";
import "styles.scss";
```

`plugin-remove-empty`'s removal of the above is pretty unexpected, I would assume that any developer writing empty imports does so knowingly for the side effects. My question is therefore whether it would be valuable to turn this transformation off by default, in order for Putout's defaults to seem more helpful and sensible to the general developer.

This is just a suggestion, if you disagree please feel free to just close this issue.

**Comment by coderaiser** [comment]
Thank you this is a good idea. 
In `eslint-plugin-putout` there is an `ide` way of using, and [it disables most dangerous rules](https://github.com/coderaiser/putout/blob/master/packages/eslint-plugin-putout/lib/index.js). I thought about making an option which will disable such rules. Anyways for now I think the best way would be to set `baseline` with `—disable-all`.

Related to https://github.com/coderaiser/putout/issues/65
