### ISSUE TITLE
feat: remove relative require to node_modules

### ISSUE THREAD

**Issue by milahu** [coderaiser/putout#79]
solution in bash:

```bash
find . -name '*.js' -or -name '*.ts' | while read f
do
  echo "$f"
  sed -E -i "s|require\('(\\.\\./)+node_modules/(.*?)'\)|require('\2')|" "$f"
done
```

sample from [github.com/aethereans/aether-app](https://github.com/aethereans/aether-app/tree/master/aether-core/aether/client/src/app)

```diff
-const minimatch = require('../../node_modules/minimatch')
+const minimatch = require('minimatch')
```

[convert-commonjs-to-esm](https://github.com/coderaiser/putout/tree/master/packages/plugin-convert-commonjs-to-esm) breaks these imports:

```diff
-const minimatch = require('../../node_modules/minimatch')
+import minimatch from '../../node_modules/minimatch.js';
```

**Comment by coderaiser** [comment]
What purpose of using such way of `require`? Why don't you just use `require('minimatch)` from the beginning?

**Comment by milahu** [comment]
> Why don't you just use `require('minimatch)` from the beginning?

dont ask me : D

just found that eslint has a [no-relative-packages](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-relative-packages.md) rule -> closing
