### ISSUE TITLE
Some dependencies are extraneous

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#92]
For example, the `try-catch` is used here:

https://github.com/coderaiser/putout/blob/68d270702089d7fe21427271c334b1f6048cc319/packages/engine-parser/lib/second-chance.js#L3

but it's declared in `devDependencies`, not `dependencies`:

https://github.com/coderaiser/putout/blob/68d270702089d7fe21427271c334b1f6048cc319/packages/engine-parser/package.json#L48-L68

And if you use Yarn v3, it will give you the following error:

```text
Error: Failed to load plugin 'putout' declared in '.eslintrc.json » eslint-config-hardcore » ./base.json': @putout/engine-parser tried to access try-catch, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: try-catch
Required by: @putout/engine-parser@npm:4.9.0 (via /Users/evgeny/Downloads/next-ts/.yarn/cache/@putout-engine-parser-npm-4.9.0-40929d5a11-78a1d5c5c8.zip/node_modules/@putout/engine-parser/lib/)

Require stack:
- /Users/evgeny/Downloads/next-ts/.yarn/cache/@putout-engine-parser-npm-4.9.0-40929d5a11-78a1d5c5c8.zip/node_modules/@putout/engine-parser/lib/second-chance.js
```

The solution for this particular case is to move `try-catch` from `devDependencies` to `dependencies`.
But I suspect there might be similar problems in other Putout packages, so I would highly recommend enabling the [`import/no-extraneous-dependencies`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) rule and checking all Putout packages.

Original issue: https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/385.

**Comment by coderaiser** [comment]
Thank you! Fixed in `@putout/engine-parser v4.9.1` 🎉 , is it works for you?

**Comment by coderaiser** [comment]
> But I suspect there might be similar problems in other Putout packages, so I would highly recommend enabling the import/no-extraneous-dependencies rule and checking all Putout packages.

Thanks :), just added.

**Comment by EvgenyOrekhov** [comment]
It works now! Thanks for a quick fix!
