### ISSUE TITLE
remove-unused-variables: False positive when only referenced in class initializer

### ISSUE THREAD

**Issue by adamdicarlo** [coderaiser/putout#96]
The `remove-unused-variables` rule is reporting variables as unused, when they are actually used. This happens when the only place the variable is used is within a class member initializer.

putout v24.5.0
no command line flags; I'm just running `putout <filename>`.

Examples:

```js
import thing from "./thing";

const pi = Math.PI;

export default class {
    static t = thing;
    static mathPi = pi;
    t = thing;
}

/* Output from putout:
foo.mjs
 1:7  error   "thing" is defined but never used  remove-unused-variables 
 3:6  error   "pi" is defined but never used     remove-unused-variables */
```

```typescript
import thing from "./thing";

export default class {
    public static t = thing;
    public t = thing;
}

/* Output from putout:
foo.ts
 1:7  error   "thing" is defined but never used  remove-unused-variables 
 3:6  error   "pi" is defined but never used     remove-unused-variables */
```

**Comment by coderaiser** [comment]
Thanks a lot :)! Landed in [@putout/plugin-remove-unused-variables](https://github.com/coderaiser/putout/tree/master/packages/plugin-remove-unused-variables#readme) @`3.8.0` 🎉 . Is it works for you?
